### ISSUE TITLE
Unified NLP not working on self-compiled AOSP 7

### ISSUE THREAD

**Issue by danielegobbetti** [microg/android_packages_apps_UnifiedNlp#102]
Background info here:
https://github.com/microg/android_packages_apps_GmsCore/issues/216
I was directed here to check #55 but I couldn't find any overlay that would interfere with the Android 6 patch (which adds the required package name to the framework).

**Comment by danielegobbetti** [comment]
I recompiled and signed with the platformkey. The app is still installed in /data. The warnings went away but the location provider still does not work. The microg's settings don't show the tick next to "UnifiedNlp is registered in system".

**Comment by mar-v-in** [comment]
did you reboot after installation?

**Comment by danielegobbetti** [comment]
Yes! I also tried several location provider just to be sure.

**Comment by mar-v-in** [comment]
Just to verify: Self-Check has everything ticked but "registered in system" and "has known location"?

**Comment by danielegobbetti** [comment]
That is correct. Everything ticked beside "registered", further no last known location present  and no update within 10 seconds " warnings".

**Comment by mar-v-in** [comment]
Confirmed and reported upstream https://code.google.com/p/android/issues/detail?id=226358. Until now it should be enough to put the app into /system. Updates can still be installed to /data as long as a copy in /system is present.

**Comment by danielegobbetti** [comment]
Thanks a lot! It's a pity seeing aosp getting more and more crippled with each release :-/

**Comment by IzzySoft** [comment]
@danielegobbetti one of the reasons I'm still sticking to LP. Sadly.

**Comment by danielegobbetti** [comment]
@IzzySoft Android 6 worked well for me with microg.

**Comment by n76** [comment]
@IzzySoft Like @danielegobbetti I've been using Android 6 with no issues. I self-compile AOSP so with the signature spoof changed needed for GmsCore and I've been running GmsCore with its built-in UnifiedNLP.

**Comment by IzzySoft** [comment]
@danielegobbetti @n76 I wasn't so much speaking of microG (pretty sure it will do its job), but e.g. hat the crippled permission system in mind. I guess *Xprivacy* should do its job independently from that (as it doesn't care about those "declarative permissions" but rather covers "functionalities/interfaces") – but before someone confirms "with enthusiasm and authority" that's the case I'll stay hesistant :)

**Comment by danielegobbetti** [comment]
OK, I took the opposite approach and patched the aosp file responsible for the additional check. I can confirm that the change works (all checks are green now, and unifiednlp started working immediately) with no apparent drawback.

Do you want me to make a pull request with the patch for android N?

**Comment by mar-v-in** [comment]
@danielegobbetti Thanks for your work.

If you can setup a PR with the patch required to run UnifiedNlp (not the signature patching of GmsCore) in a `patches/` subfolder.

If you don't mind, it would also be awesome if you push the patch to CM and OmniROM gerrit, but I can do this as well if you want.

**Comment by danielegobbetti** [comment]
@mar-v-in closing this in favor of #103. I'd prefer if you could do the push to Omnirom and other ROMs. I am available to test other approaches if there are suggestions!

**Comment by nikolowry** [comment]
Big fan of microg and the effort to make FOSS Android usable again - so first thanks for the continued work!

I'm on the 0.2.4-22-gcb356d2 gmscore build (with UnifiedNlp) and found this issue after about two weeks of not being able to get location to work.

I didn't have any plans (or time) to compile/flash my own rom, so I booted into recovery, mounted `/system` and copied the following to `/system/priv-app`:
- com.google.android.gms-1
- com.google.android.gsf-1
- org.fitchfamily.android.wifi_backend-1
- org.fitchfamily.android.gsmlocation-1
- org.microg.nlp.backend.ichnaea-1
- org.microg.nlp.backend.nominatim-1

Obviously I didn't know if I should just copy com.google.android.gms-1 or if the gsf framework and backends needed to be in `/system/priv-app` as well - so I just played it safe and copied them all.

Point being, it might be really helpful for other users like myself who align with the FOSS mentality but aren't Android-first devs/tinkers, if the wiki was updated with a note concerning which apk{s} needs to be copied to `/system/priv-app` until the newer builds are stable.

**Comment by ale5000-git** [comment]
@nikolowry: Installing it manually in the system partition is likely to cause problems since there are many things to consider and it differs on various Android version.

To do it more easily you could try my [flashable ZIP](https://forum.xda-developers.com/showthread.php?t=3432360)
Note: In case you try remove the files you have already copied before installing the ZIP.
