### ISSUE TITLE
UnifiedNlp is not registered in system

### ISSUE THREAD

**Issue by ale5000-git** [microg/android_packages_apps_UnifiedNlp#104]
Quote from mandayugana's [post](http://forum.xda-developers.com/showpost.php?p=69964961&postcount=207) to keep track of the problem.

> Currently I'm using Samsung 4.1.2 firmware. I have successfully removed Google and Samsung apps from system. But I have an issue that UnifiedNlp is not registered in system. It is finally registered after adding the third line into Manifest.xml.

```
        <service android:exported="true" android:name="org.microg.nlp.location.LocationServiceV1" android:permission="android.permission.ACCESS_COARSE_LOCATION">
            <intent-filter>
		<action android:name="com.android.location.service.NetworkLocationProvider"/>
                <action android:name="com.google.android.location.NetworkLocationProvider"/>
            </intent-filter>
            <meta-data android:name="serviceVersion" android:value="1"/>
            <meta-data android:name="version" android:value="1"/>
        </service>
```

**Comment by ainola** [comment]
Can confirm that this occurs on Cyanogenmod 14.1 (nightly 2016-12-08)

**Comment by fw190** [comment]
I can confirm. Nexus 4 cyanogenmod 14.1 nightly 2016-12-10

**Comment by mar-v-in** [comment]
CM14.1 is a different problem. Android 7.0 no longer supports NLP overlays not shipped with the ROM. There is a patch in the `/patches/` folder of this repo that has to be applied to CM first.

**Comment by fw190** [comment]
How can I apply this patch? Should I flash it with TWRP?

**Comment by mar-v-in** [comment]
It's a source code patch that has to be applied by the CM team. Afaik, there is no tool allowing to patch a system after installation so far (but it might be that there will be one sometime). Alternatively you can of course ask CM team to include [the patch](https://github.com/microg/android_packages_apps_UnifiedNlp/blob/master/patches/android_frameworks_base-N.patch) so that future versions of CM work out of the box.

**Comment by fw190** [comment]
I have asked at xda and at their forums. Could the patch creator make a pull request?

**Comment by Roxxor91** [comment]
I agree. The patch already exist, so it would be nice if we could try to have this integrated into CM. (If the CM team approves)
@danielegobbetti 
As you are the original author, would you mind making a pull request? Or if you dont feel like it and allow me to, I could also try to do the request. Never did something like that and I am not a programmer, but I could try.

Off topic: Seems like you are everywhere, where I am (only more productive). MicroG, Gadgetbridge, FreeXperia, Conversations.. Thanks for helping making free software great!

**Comment by 7lb** [comment]
I'd also be willing to open a pull request if @danielegobbetti is unable or unwilling to do it.

I've forked the upstream branch and committed the patch (commit [here](https://github.com/7lb/android_frameworks_base/commit/0f26a3992286a6e0fe9397fcdbd7b298ea68347f)) already, but I'm waiting for the author's permission before opening a pull request

**Comment by ale5000-git** [comment]
I doubt they will accept it, since it have pro and contro.

**Comment by fw190** [comment]
@ale5000-git so where could we be on topic?

What do you mean with pro and contro?

What can we do to have gps without the need to install google apps? RIght now our phones doesn't have working gps.

**Comment by ale5000-git** [comment]
@fw190: I suggest to open a separate issue.

The change limit location providers to only system apps, with the patch any app can become a location provider.
If you install UnifiedNlp in /system/priv-app/ then it will work even without the patch.

**Comment by danielegobbetti** [comment]
Sorry but I'm not willing to interact with the ROM maintainers but feel free to do so and request that they include the patch. See my comment in the original issue: https://github.com/microg/android_packages_apps_UnifiedNlp/issues/102#issuecomment-256998826

**Comment by mandayugana** [comment]
Thanks, @ale5000-git, for bringing this issue here. UnifiedNlp is working fine on Lollipop 5.1.1. This issue arises in JB 4.1.2. Installing UnifiedNlp as system app doesn't help.

**Comment by ninep9up** [comment]
Any progress with 4.1?
