### ISSUE TITLE
Doesn't work well ?

### ISSUE THREAD

**Issue by Paviluf** [microg/android_packages_apps_UnifiedNlp#105]
Hello,

I don't know if it's UnifiedNlp or the backend (IchnaeaNlpBackend) that doesn't work well but often my map apps can't find my location. I use maps.me and osmand. Here are the problems I have :

- Sometimes the location is never found
- Sometimes the location is totally wrong (100+ km)
- Sometimes the location is quite imprecise (200+ km radius)
- Sometimes the location is wrong and correspond to the location where the last time I used the map apps

Here is a log that show that osmand find me, then lost the location, and find me again. I will provide more logs if needed when problems appears.

[2016-12-13-07-25-14.txt](https://github.com/microg/android_packages_apps_UnifiedNlp/files/648144/2016-12-13-07-25-14.txt)

Thanks !

**Comment by Paviluf** [comment]
Here is some more logs

- maps.me show my previous location
[2016-12-14-12-41-51.txt](https://github.com/microg/android_packages_apps_UnifiedNlp/files/652814/2016-12-14-12-41-51.txt)
- osmand can't find the location
[2016-12-14-12-43-06.txt](https://github.com/microg/android_packages_apps_UnifiedNlp/files/652821/2016-12-14-12-43-06.txt)

**Comment by Paviluf** [comment]
By the way I'm on CM11 (Razr i)

**Comment by Paviluf** [comment]
It seem that UnifiedNlp 1.6.6 works much better. I will make more tests.

**Comment by Paviluf** [comment]
Ok v1.6.6 worked well this morning but failed this afternoon.

- osmand and maps.me found me in the middle of water 7 kms away from my real location
[2016-12-15-12-34-54.txt](https://github.com/microg/android_packages_apps_UnifiedNlp/files/655296/2016-12-15-12-34-54mapsmewrong.txt)
[2016-12-15-12-36-44.txt](https://github.com/microg/android_packages_apps_UnifiedNlp/files/655297/2016-12-15-12-36-44osmandwrong.txt)

**Comment by n76** [comment]
FWIW, the backend(s) are the real provider of location. UnifiedNLP pulls together the location estimates for all installed and enabled backends and then gives you the one with the smallest estimated error.

So this bug should be placed against the IchnaeaNlpBackend backend instead of UnifiedNLP.

And there are other backends that you can install and use which might give better results for you.

Also, several of the backends use open source mobile/cell tower location estimates. You can improve the accuracy of most of the backends by contributing to projects like Open Cell ID or Mozilla Location Services.

**Comment by Paviluf** [comment]
The last time it was UnifiedNLP that wasn't working https://github.com/microg/android_packages_apps_UnifiedNlp/issues/80

I live in Bordeaux, France and there is plenty of wifi and 2G, 3G around. The thing is that at a given location sometimes that work, sometimes not.

**Comment by Paviluf** [comment]
Is there something I can do to found if the problem is in UnifiedNLP ?

**Comment by n76** [comment]
Use an app like [SatStat](https://f-droid.org/repository/browse/?fdfilter=satstat&fdid=com.vonglasow.michael.satstat) that shows both the GPS location and the "network" location. Then try different backends. You may find that different backends perform differently.

FWIW, I've played with all the backends and they do return different results. And when writing my own backends I've never noticed UnifiedNLP corrupting the data my backends created: If there was a position problem it was with the backend not UnifiedNLP.

**Comment by Paviluf** [comment]
By the way I meant that doesn't work well with GPS disabled (disabled or in buildings). With GPS the location is found quickly. When GPS is not available UnifiedNLP should locate me, not accurately but I think in a range of 100m to 1km based on wifi and gsm, and that often not the case. As I said in the first post and I repeat without GPS:

- Sometimes the location is never found
- Sometimes the location is totally wrong (100+ km)
- Sometimes the location is quite imprecise (200+ km radius)
- Sometimes the location is wrong, not updated, and correspond to the location where the last time I used the map apps

- IchnaeaNlpBackend: work very well sometimes, but don't update the location sometimes.
- OpenBmapNlpBackend: imprecise and not reliable for me (found me in Paris ~500km away with wifi)
- LocalGsmNlpBackend: not very precise (10km radius) so I don't know if it update the location correctly

**Comment by Paviluf** [comment]
As I said there https://github.com/microg/IchnaeaNlpBackend/issues/27
> Well I don't know if it's the problem lies in the backend or in UnifiedNlp because it kind of happened too with LocalGsmNlpBackend when I was in Andernos, France yesterday. I tried 3 or 4 times to see if I was correctly located and that was not the case until maybe the 5th time. There was plenty of GSM antennas available and I didn't move at all when I was located.

> Here is a log when that didn't worked with LocalGsmNlpBackend
[2016-12-24-17-50-00.txt](https://github.com/microg/IchnaeaNlpBackend/files/672251/2016-12-24-17-50-00.txt)

**Comment by n76** [comment]
@Paviluf I'd expect to see at least a log message from NlpLocationBackendFuser that will show what backend(s) were called and what the various backend(s) returned. I don't see that in your log so it is not possible to say what is happening.

Perhaps another log file captured using something like:

`adb logcat | grep NlpLocationBackendFuser`

would help.

**Comment by Paviluf** [comment]
For me it look like that NlpLocationBackendFuser doesn't show up because UnifiedNlp or LocalGsmNlpBackend kind of hanged or crashed.

**Comment by n76** [comment]
Maybe. While I haven't seen LocalGsmNlpBackend crash on a version I've released, I would not rule it out. But I've never seen UnifiedNlp crash so that would surprise me a lot.

**Comment by Paviluf** [comment]
I don't know if it can be related but my phone is a x86 (Motorola Razr i).

**Comment by n76** [comment]
[LocalGsmNlpBackend](https://f-droid.org/repository/browse/?fdfilter=unified&fdid=org.gfd.gsmlocation) or [Local-GSM-Backend](https://f-droid.org/repository/browse/?fdfilter=unified&fdid=org.fitchfamily.android.gsmlocation)?

I can't help much on LocalGsmNlpBackend which [looks like it was last updated three years ago](https://github.com/rtreffer/LocalGSMLocationProvider) and probably does not have current mobile/cell tower information. The Local-GSM-Backend is the one I support and allows you to download current data from a couple of different sources.

**Comment by Paviluf** [comment]
I use the more recent one [Local-GSM-Backend](https://f-droid.org/repository/browse/?fdfilter=unified&fdid=org.fitchfamily.android.gsmlocation) with the data for France.

**Comment by n76** [comment]
And what is the output from the logcat command I suggested earlier. I would expect something like

`12-25 13:24:51.405  1568  2030 V NlpLocationBackendFuser: location=Location[network 33.000000,-117.000000 acc=19 et=+1h2m21s719ms {Bundle[{noGPSLocation=Location[network 33.000000,-117.000000 acc=19 et=+1h2m21s719ms], AVERAGED_OF=7, SERVICE_BACKEND_PROVIDER=wifi, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.wifi_backend/.backend.BackendService_}]}]`

(I've munged the lat/lon for privacy. I don't have a SIM card in the phone I've got microG installed on so I don't get any mobile/cell towers but NlpLocationBackendFuser should still show something just different than what mine is showing).

**Comment by Paviluf** [comment]
Here is the output of `adb logcat | grep NlpLocationBackendFuser`

`V/NlpLocationBackendFuser( 3942): location=Location[network 44,865632,-0,592449 acc=1655 et=+1d16h36m4s518ms {Bundle[{noGPSLocation=Location[network 44,865632,-0,592449 acc=1655 et=+1d16h36m4s518ms], AVERAGED_OF=8, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GsmService_}]}]`

**Comment by Paviluf** [comment]
It seem the problem is in IchnaeaNlpBackend. https://github.com/microg/IchnaeaNlpBackend/issues/27#issuecomment-274408739

**Comment by Paviluf** [comment]
If I use LocalGsmNlpBackend for 2G/3G and IchnaeaNlpBackend for wifi it work very well. So it really don't seem to be a UnifiedNlp problem.
