### ISSUE TITLE
UnifiedNlp works on Cyanogenmod 9 but not on 10

### ISSUE THREAD

**Issue by aktivkohle** [microg/android_packages_apps_UnifiedNlp#107]
So from [here](https://download.cyanogenmod.org/?device=smultron) I originally flashed the newest nightly cm-10-20131006-NIGHTLY-smultron.zip onto the Sony Ericsson Xperia Mini and the UnifiedNlp (legacy) from F-droid would not work. Then eventually as maps were important to me I flashed the newest stable cm-9.1.0-smultron.zip onto the device. Here I got it to work, but felt that was mainly through using /system/app mover to move UnifiedNlp to be a system app. After reboot all or most of the boxes in UnifiedNlp were ticked and it worked wonderfully with either MozillaNlpBackend or LocalGsmNlpBackend (with the offline DB), the device finding itself quickly in OsmAnd~ and network/GPS locations in the small Here GPS Location app

A few weeks went by and I noticed that the stable CM-9 had no FM radio like 10 did. Realising I couldn't install one I thought that the network location mainly worked as I had made it into a system app and rebooted. So feeling adventurous, I went from 9 back up to CM-10 and now I've got the FM radio back but even with UnifiedNlp as a system app it will not work! Android-Version is 4.1.2 .  Only the "system supports" and "backend is set up" boxes are ticked under CM-10

Does anyone have a clue why this is not working with CM-10 when it works so easily in CM-9 and if there is any way to fix it, patches etc?

**Comment by aktivkohle** [comment]
Guys, since nobody seemed to have any ideas, I've put CM-9 back onto the device and UnifiedNlp is working fantastically again; 5 thinks in the self-check are ticked and it finds itself quickly. 

Location finding is more important than the FM radio, there's plenty other things to listen to if necessary and I think putting the FM radio onto CM-9 would be easier than getting UnifiedNlp to work on CM-10. I might post about that in an appropriate forum. Many things seem to run faster on CM-9 than with CM-10 on this 2011 device anyhow.

**Comment by ale5000-git** [comment]
@aktivkohle: I suggest CM11, it is the fastest (not sure for your device but in general it is).

**Comment by aktivkohle** [comment]
Thanks @ale5000-git I didn't know, officially the device only does 7, 9 and 10.
https://download.cyanogenmod.org/?device=smultron

Can see that unofficially people have been experimenting with 11 on it
http://forum.xda-developers.com/showthread.php?t=2545367
https://www.youtube.com/watch?v=qK12mdP_mVs

Anyway, might try that some time, although almost everything works on it at the moment other than the FM radio, but still need to test the substitute for play services.

**Comment by ale5000-git** [comment]
@aktivkohle: Try to remove UnifiedNlp and install microG Services Core 0.2.4-**39** or later.

This version of microG Services Core include the NOT-Legacy UnifiedNlp with the fixed #104 that probably fix your problem.

PS: Ignore the notice that say that your Android version is not supported (it doesn't mean that it will not work but just that is not tested).

**Comment by aktivkohle** [comment]
Hey @ale5000-git am very sad to say that even after a lot of effort, MicroG Services Core 0.2.3-39-ga53b32e is still not working on Cyanogenmod 10 on my device, despite going to all the effort with Haystack (linked above) and getting signature spoofing working. 

**Ticked** in microG Services Core are:
System spoofs signature
Play Services (GmsCore) installed
Play Services  (GmsCore) had correct signature
Play Store (Phonesky) installed
Play Store (Phonesky) had correct signature
Services Framework (GSF) installed
Location backend is set up

**Not ticked** are:
System supports location provider
UnifiedNlp is registered in system
Network-based location enabled.

Network-based location in the settings definitely IS enabled so not sure what is wrong there. I've also tried moving MicroG core to a system app and rebooting which is what fixed the "registering in system" in Cyanogen 9 but it is still not working :(

Say if you have any ideas I'll try it, seems a pity after all this effort to give up on it..

**Comment by ale5000-git** [comment]
It is strange, maybe try to post a logcat so we can see if there is something that can help to discover the problem.

**Comment by aktivkohle** [comment]
Thanks, that's the first time I've ever done that..

`Typed in adb logcat -v long > problem2.txt`

First did it just playing around on the phone then rebooted. ADB closed itself so I quickly re-entered the command above with a 2 on the end of the filename. After reboot I opened up OsmAnd and tapped the location button a few times. In the course of about 30 seconds for rebooting and opening that app it created a 446kB file! Never knew it was so busy..

Can see the terms 'microg', 'osm', 'nlp' each occur several times in the document but I wouldn't know what to look for. I've uploaded it, thanks for your help..  Below are a few suspect examples from this file:

```
[ 12-27 20:18:40.267   403:  435 W/PackageManager ]
Permission org.microg.permission.FORCE_COARSE_LOCATION from package com.google.android.location ignored: original from com.google.android.gms
``` 
```
[ 12-27 20:19:32.474  1103: 1103 D/GmsGcmTrigger ]
Ignoring Intent { act=android.net.conn.CONNECTIVITY_CHANGE flg=0x8000010 cmp=com.google.android.gms/org.microg.gms.gcm.TriggerReceiver (has extras) }: gcm is disabled
```

[problem2.txt](https://github.com/microg/android_packages_apps_UnifiedNlp/files/674577/problem2.txt)

**Comment by ale5000-git** [comment]
I think it is related to this:
> Not granting permission android.permission.INSTALL_LOCATION_PROVIDER to package com.google.android.gms (protectionLevel=18 flags=0x83e44)

but we should wait response from @mar-v-in

**Comment by mar-v-in** [comment]
On legacy systems you need to install Legacy version as documented in README even when using microG Services Core. There is an issue in the last legacy version release that is already fixed in the master but without build so far.

**Comment by aktivkohle** [comment]
Thanks @mar-v-in I can see that you added something to the master 6 days ago, maybe that was it. One extra line went into AndroidManifest.xml

I might have to just wait. Had a go, installed Gradle, cloned the repository locally, but it looks like you have to actually know what you are doing with building for android, not just entering a few lines on the command line.

Ok, so the versions in F-droid were not new enough. I had both apps (legacy version +  core) installed yesterday and briefly all boxes were ticked, but it still wasn't working and the system was unstable, especially crashing any app that uses location. I needed to use a sport app, so have temporarily uninstalled microG and wait a minute or two for the GPS to find itself. Anyway will be good to see this work on Cyanogenmod 10, say if you have any links or tips for building it might try again.

**Comment by ale5000-git** [comment]
@aktivkohle: Try the new version.

**Comment by aktivkohle** [comment]
Thanks :) Can see a version 1.6.8 is prepared for release, can't find an apk in this repository yet and F-Droid is still sitting on 1.6.7 will wait a few days but paste a link if you know where it is..

**Comment by ale5000-git** [comment]
Currently it is only [here](https://github.com/microg/android_packages_apps_UnifiedNlp/releases).
I think it will appears also in other places in some days.

**Comment by ale5000-git** [comment]
@aktivkohle: Currently it is only [here](https://github.com/microg/android_packages_apps_UnifiedNlp/releases).
I think it will appears also in other places in some days.

**Comment by aktivkohle** [comment]
@ale5000-git it works!!!!!  

So now I've got the FM radio and the network location services, it's finding itself in under ten seconds rather than taking a whole minute and that circle with the location is showing on OsmAnd, also Here GPS is confirming GPS location. 

I installed just Legacynetworklocation.apk and nothing else from your link above. After initial reboot was half working but there were messages it was crashing. Moved it to a system app and rebooted and now under self-check all boxes are ticked:

- System supports location provider
- UnifiedNlp is registered in system
- Location backend(s) set up
- Network-based location enabled
- UnifiedNlp has known location
- UnifiedNlp provides location updates

So thanks to @mar-v-in for that. Even before this, my sports tracking app works without google play services but some other apps like the taxi one do not.  Does not seem that urgent, but perhaps that "MicroG core" will make that possible, with that signature spoofing modification to the settings that took so much effort. Bit scared to break something that is now working well thought.. :)

**Comment by ale5000-git** [comment]
@aktivkohle: Signature spoofing is easy with Tingle and can be rolled back if needed.
The app create a backup file, just keep it on the pc.

**Comment by ale5000-git** [comment]
@aktivkohle: If the problem is fixed please close the issue.

**Comment by aktivkohle** [comment]
Yes, sorry @ale5000-git I am closing it now. Have had this UnifiedNLP working for months and months now on Cyanogenmod 10 on the Xperia mini and enjoying the FM radio too :)
