### ISSUE TITLE
No gapps unifiednlp with gapps.

### ISSUE THREAD

**Issue by h1p3rbr0** [microg/android_packages_apps_UnifiedNlp#108]
Guys, hi, i'm stupid and install no gapps version with gapps for my Galaxy s4. But when i try uninstall it - have error. Can you send me step-by-step uninstall guide, please?
p.s. sorry for my english

**Comment by mar-v-in** [comment]
If you have GAPPS installed it's not possible to install the no gapps version. F-Droid is just showing it wrong in that case.

**Comment by IzzySoft** [comment]
F-Droid just compares by the package name. And in this case, the package names are identical – so it sees the original GApps and thinks it's mar-v-in's. The F-Droid app being unable to *uninstall* the app shows it's a system app (not installed via F-Droid), and thus backs that claim.

So, if you're really installed it via F-Droid: No worries. You wouldn't be able to install the mentioned app on top of the already installed GApps (F-Droid would throw a warning pointing out a "signature mismatch" instead) – so don't let that confuse you :smile_cat:

**Comment by h1p3rbr0** [comment]
I uninstall f-droid and install it again, repository name changed automatically, but i changed it again. Anyway unified nlp adding to list automatically too.
Send me easy way how delete this app from F-droid list, because this confuse me and don't looks like good apps build.

**Comment by h1p3rbr0** [comment]
I mean, estetically this looks like ****

**Comment by ale5000-git** [comment]
@h1p3rbr0: You can't, until F-Droid add some support for signature spoofing in some way there will be this problem.

**Comment by ArchangeGabriel** [comment]
Which might well be never BTW, because if they can I can’t see what would block other apps to check signature spoofing from microG too…

**Comment by mar-v-in** [comment]
@ArchangeGabriel I don't see why apps should not bypass signature spoofing, technically it's not complex to do it. Of course most apps have no reason to bypass it, but the few possible reasons include F-Droid requiring it to provide a meaningful UI because ignoring signature spoofing is not an option when working with the android package manager.

@ale5000-git @h1p3rbr0 no, it's not necessary to bypass signature spoofing for this specific issue. What is required is to handle signatures on apps to filter the "Installed" apps list of F-Droid and not only when trying to update apps. Signature spoofing is a problem that only applies when the microG repo is active, because no app present in the f-droid default repo uses signature spoofing.

**Comment by ArchangeGabriel** [comment]
@mar-v-in Well, I guess this is not very hard, but hope it never spreads. Apps doing that would include anything that use SafetyNet currently I think. And probably others. Making all of μG useless in a lot of cases, which would be sad…

**Comment by h1p3rbr0** [comment]
Yeah, i start thread about this, believe in true place
https://gitlab.com/fdroid/fdroiddata/issues/569

**Comment by IzzySoft** [comment]
@h1p3rbr0 when it turns up in updates, open its entry. Then tap the "overflow menu" (the 3 stapled dots in the upper right corner), and tell the F-Droid app to "always ignore it". Done. Marvin cannot change the package name, as with a different package name it would not work – other apps expect exactly that package name to be present.

**Comment by h1p3rbr0** [comment]
"Always ignore updates"?

**Comment by IzzySoft** [comment]
Yes. Then it at least stops offering you that – which should help minimize confusion ;)

**Comment by h1p3rbr0** [comment]
But anyway i will see it in my app list... mhm

**Comment by IzzySoft** [comment]
Yeah, that can't be helped AFAIK. But at least it won't nag you. I have that issue with multiple apps, especially some that came preinstalled with CM and are not signature-compatible. This must be fixed on F-Droid's end: as they use the same key for all APKs, they could check the local ones if they use a different one and then exclude them (or at least gray them out). But as said, there's nothing Marvin can do about.
