### ISSUE TITLE
Xposed Framework support

### ISSUE THREAD

**Issue by Djfe** [microg/android_packages_apps_UnifiedNlp#12]
is it possible to add UnifiedNlp to your system usign the Xposed Framework?
If so that would be great.
#9 wouldn't be an issue anymore as the app could handle conflicts using the xposed framework.

you would be able to add unifiednlp settings to the system settings->location settings page

people would be able to use UnifiedNlp without the risk to "destroy" their ROM, because they are able to deactivate it anytime they want

**Comment by mar-v-in** [comment]
https://github.com/Rawi01/XposedUnifiedNlp

**Comment by Djfe** [comment]
nice
Hopefully the dev will upload a version to the Xposed Repo soon :)

**Comment by Djfe** [comment]
are you going to work together with Rawi01 btw.? (or will Rawi01 just merge the upstream into his repo?)

**Comment by Rawi01** [comment]
I uploaded it two minutes ago :)
