### ISSUE TITLE
[Q] Using both UnifiedNlp and GApps without Xposed

### ISSUE THREAD

**Issue by breversa** [microg/android_packages_apps_UnifiedNlp#133]
Hi,

Is it possible to use UnifiedNlp on a phone using GApps (basically only Play Store and necessary parts) ?

I used to use XposedUnifiedNlp on CyanogenMod 13, but I'd like to switch to LineageOS 14 for which Xposed isn't available (yet or never).

What I'm aiming at is :
- LineageOS
- Play Store (and its dependencies)
- NO other Google service
- UnifiedNlp to allow the use of other location providers

**Comment by ale5000-git** [comment]
Isn't easier to use microG with Play Store?

**Comment by breversa** [comment]
Is microG compatible with Play Store ?

**Comment by ArchangeGabriel** [comment]
Yes. They are people using the original Play Store, and where even able to make (in-app) purchase working.

**Comment by breversa** [comment]
So basically, I need to install microG, then get the phonesky.apk somewhere (most probably from opengapps) and drop it to /system/app ?

**Comment by ale5000-git** [comment]
Yes, but phonesky.apk must be in /system/priv-app.

There is also my installer that do this automatically: [microG unofficial installer](https://forum.xda-developers.com/showthread.php?t=3432360).

**Comment by breversa** [comment]
Thank you @ale5000-git ! I gave it a try, and long story short, here's a bug report for you : https://github.com/ale5000-git/tingle/issues/33

**Comment by ale5000-git** [comment]
@breversa: Have you been able to setup everything?

**Comment by breversa** [comment]
Almost ! Using tingle, I managed to install microG on LineageOS 14.1, however, the self-check still doesn't tick the "UnifiedNlp is registered in system" (even after a reboot). :-(

Any idea why not ?

**Comment by ale5000-git** [comment]
@breversa: On Android 7 microG GmsCore need to be installed as system app (or applying another patch to Android) to bind it correctly to the system.

**Comment by breversa** [comment]
Silly me, I should have re-read the instructions. Now it works. Thank you ! :-)

(I actually did not set up Play Store, but Yalp Store instead : https://fossdroid.com/a/yalp-store.html)

**Comment by ale5000-git** [comment]
If everything is fixed, can you close the issue please?

**Comment by breversa** [comment]
Sure thing !
Thanks again ! :-)
