### ISSUE TITLE
apps which do not work with MicroG

### ISSUE THREAD

**Issue by herrdeh** [microg/android_packages_apps_UnifiedNlp#137]
On my system (MicroG 0.2.4-79-g7f13738, CM 6) everything used to be fine, but recently a number of new installed apps are requesting either "update google play" or "install google play". I'm providing a (yet quite short) list of those - maybe other fellows want to contribute:

- Free2move https://play.google.com/store/apps/details?id=com.ghm.carjump (Google Play Services have to be installed in order to use Free2move)
- Urbi https://play.google.com/store/apps/details?id=com.batsharing.android (urbi can only be executed when you update your Google Play services)

**Comment by ale5000-git** [comment]
Well, you are using an old version.
The latest version is 0.2.4-92 (0.2.4-81 is suggested for Android < 5 for a bug in the latest version).

Now that I think about it, CyanogenMod 6 is based on Android 2.2, so you cannot have installed microG or you reported the wrong version.

**Comment by herrdeh** [comment]
Ufff&sorry - all my fault...

I'm using CM13, based on Android 6. 
And actually I found that I could update to -92, and that this solved my problems. Thank you, man!

What caused this trouble was that I did not receive the MicroG core update when updating all my F-Droid apps, I had to do the update manually. Donno why, maybe the update to F-Droid 0.102.3 will solve this.

Cheers,
Wolf

**Comment by ale5000-git** [comment]
@herrdeh: The latest version of F-Droid is 0.103.1

**Comment by herrdeh** [comment]
Hm. This is strange. My F-Droid offered 0.102.3 for update - now the list of apps "ready to update" is empty. But when I look for the F-Droid app in the "all available" list, I can find the 0.103.1 there. Same thing as with MicroG. Right - I'll try to figure that out with F-Droid people.
