### ISSUE TITLE
how to import com.android.location.provider.LocationProviderBase ?

### ISSUE THREAD

**Issue by ofskymohsen** [microg/android_packages_apps_UnifiedNlp#138]
I am writing a custom network location provider like UnifiedNLP . In order to create an unbundled location provider we should inherit from LocationProviderBase . But this class is not in Public SDK . How you import this class in  LocationProviderV2 class ? I saw LocationProviderBase is @hide and we cannot use in code in IDE .

**Comment by gdt** [comment]
Why are you writing something like UnifiedNLP instead of a plugin for UnifiedNLP for a particular service?   Perhaps you could file bug/enhancement requests for the reasons that are leading you to want to do this.
