### ISSUE TITLE
Failure: Register for Push Notifications

### ISSUE THREAD

**Issue by 74cmonty** [microg/android_packages_apps_UnifiedNlp#140]
Hello!
I have installed
- GMSCore 0.2.4-103 (preview)
- Xposed Framework ver 87
- FakeGapps 1.1
- XposedGmsCoreUnifiedNlp 1.0.4-beta
on LineageOS-13.0-20170211-Stable.

The function "Self Check" in GMSCore reports no errors (see [here](https://ibb.co/eF7ph5), [here](https://ibb.co/n3djFQ), and [here](https://ibb.co/jCBt9k)).
In GMSCore I have [checked](https://ibb.co/dWmh25) "Google Cloude Messaging".

To verify if push notification is working, I use app "Push Notification Tester version 2.5".
And this tool reports:
- [Google Play Services are not available](https://ibb.co/e1PAN5)
- Play Services Installed - [false](https://ibb.co/cwdtaQ)
- Register for Push Notifications - [false](https://ibb.co/cwdtaQ)

The error "Google Play Services" is also reported by other apps, e.g. [Burger King](https://ibb.co/j78gUk).

Presuming this is not a false fault, how can I fix this?

THX

**Comment by ale5000-git** [comment]
It is normal since you dont have installed PlayStore or FakeStore.

**Comment by n76** [comment]
ale5000-git has your answer. You need to have something to fake apps into thinking Play Store is installed. The general recommendation is to use FakeStore but I happen to use BlankStore.

FWIW, I installed a Push Notification Tester with a version of 2.5 (there are more than one "Push Notification Testers" on Play Store according to Yalp) and the Burger King app. The Push Notification Tester reported success and the Burger King app seems to work okay (showing there are no Burger Kings near me).

**Comment by 74cmonty** [comment]
OK. I didn't install any fake app, yet.
Could you share your input regarding the differences of fake stores
- Blankstore
- [Phonesky](https://github.com/microg/Phonesky)
- [Fakestore](https://github.com/microg/android_packages_apps_FakeStore)

**Comment by ale5000-git** [comment]
FakeStore is a dummy one; it is just for "Google Play Services detection" but it doesn't do anything else (if you use a different market app like F-Droid you can use this).

The others are also real market apps but I have never used them.

**Comment by 74cmonty** [comment]
All right, after installation of FakeStore from F-Droid "Push Notification Tester" reports only 1 issue: Register for Push Notifications; please check this screenshot.

Other errors related to Google Services are solved!
![screenshot_20170802-064206 1](https://user-images.githubusercontent.com/12523591/28858032-057d2cf2-774e-11e7-9537-3e1609b5ea69.png)

**Comment by krzysztofzygmunt** [comment]
Have you ever make push notifications working ? I've exactly the same problem and get exactly the same error.
