### ISSUE TITLE
Your system does not support this UnifiedNlp package

### ISSUE THREAD

**Issue by mama-git** [microg/android_packages_apps_UnifiedNlp#144]
I have a Chinese Android watch (Android 4.4.4 API 19 - not Android Wear) on which I'm trying to install the UnifiedNlp package.

I keep getting the error "Your system does not support this UnifiedNlp package. Either install a matching package or a compatibility Xposed module." when self-checking. Alongside 2 other errors:
"The system did not bind the UnifiedNlp service. If you just installed UnifiedNlp you should try to reboot this device." (device was rebooted) and
"You either disabled network-based location (in system settings) or the system is not supported." (location is enabled and on "High Accuracy")

I tried all different versions (NetworkLocation.apk, LegacyNetworkLocation.apk, and UnifiedNlp.apk), all in vain. No version worked.

Also, installing the standalone UnifiedNlp or the one that comes witch microG does make a difference.

Am I missing something?
If the system is not supported: why? What is the cause for a system not to be supported?

**Comment by ale5000-git** [comment]
Chinese ROMs usually come with another location service that conflict.

If you want an easier way I have created an installer that automatically remove conflicting packages and works perfectly in 99% of cases: [microG unofficial installer](https://forum.xda-developers.com/showthread.php?t=3432360).

**Comment by mama-ilogs** [comment]
Thanks a lot.

I already came across your installer, but since I cannot flash anything on the device and there is no custom recovery for it, I did not try it.

Is there any other way to use your installer without flashing?

**Comment by ale5000-git** [comment]
[FlashFire](https://play.google.com/store/apps/details?id=eu.chainfire.flash) allow to flash a zip inside Android itself.

Some people reported it works but I haven't tried it.

**Comment by mama-git** [comment]
Thanks, I am still trying to root the device. As soon as I have tried flashing your installer I will report back.

**Comment by mama-git** [comment]
Thanks a lot for you help. I managed to install GmsCore correctly!

**Comment by difr** [comment]
Hi, ale5000!
I've used your installer, but have exactly same errors. Can you, please, advice me direction to dig.
It's android 5.1 (lenovo z90a40). Stock rom with gapps, which was replaced with opengapps, after was mostly removed, and after was your "microG-unofficial-installer-ale5000-v1.0.21-beta-signed.zip" flashfired.

**Comment by difr** [comment]
XposedGmsCoreUnifiedNlp works :)

**Comment by ale5000-git** [comment]
@difr: Cuold you please post a screenshot of the microG self check and a copy of /system/framework/framework-res.apk?

**Comment by difr** [comment]
@ale5000-git 
Sorry, can't provide ss now, it's not my phone. But it was exactly the same
"Your system does not support this UnifiedNlp package. Either install a matching package or a compatibility Xposed module." 
"The system did not bind the UnifiedNlp service. If you just installed UnifiedNlp you should try to reboot this device."
Which are disappeared after "XposedGmsCoreUnifiedNlp" start to work.
And here is "framework-res.apk"
[framework-res.apk.zip](https://github.com/microg/android_packages_apps_UnifiedNlp/files/1369257/framework-res.apk.zip)

**Comment by ale5000-git** [comment]
@difr
Apparently your framework-res.apk has some dependancies and I'm not able to decompile it (it is the first time that I'm seeing this).

Can you please post the entire framework folder so I can decompile it and see the problem?

**Comment by difr** [comment]
here it is
https://github.com/difr/temp/blob/master/framework.zip

**Comment by difr** [comment]
@ale5000-git 
here it is
https://github.com/difr/temp/blob/master/framework.zip

**Comment by ninep9up** [comment]
My Acer B1-A71's 6577T has an xml for specifying a location service in /etc called location_service_conf.xml. Apparently you can put gms there pointing to the core but this still doesn't work for me though now it says it's registered. Original service provider is Mediatek, but deleting it doesn't make difference. Framework-res.apk also misses lines and putting there any doesn't make any difference also.

What should I do?
