### ISSUE TITLE
Configure location backends on small devices

### ISSUE THREAD

**Issue by junvo** [microg/android_packages_apps_UnifiedNlp#148]
Hello, I installed the LocalWifiNlpBackend and I wanted to activate it, but I can´t access the checkbox or the settings icon with my device.

Is there a way to activate it via Command Line?

**Comment by n76** [comment]
Open UnifiedNlp or microG app. You activate and configure the back end settings there.

**Comment by junvo** [comment]
@n76 yes I know that I need to go to UnifiedNlp, from there the checkbox or the settings icon is not accessible for me.

**Comment by junvo** [comment]
ok I found a solution I installed this on my computer https://adakoda.github.io/android-screen-monitor/
