### ISSUE TITLE
Unable to bind with Android 8.1 (Lineage for microG)

### ISSUE THREAD

**Issue by realmain** [microg/android_packages_apps_UnifiedNlp#152]
Using [LineageOS microG fork](https://lineage.microg.org/) 15.1 for the OnePlus 3T, it looks like UnifiedNlp is unable to bind to the system. It's causing my GPS to take forever to get a location, unlike in 14.1 when UnifiedNlp is able to bind. I have **Mozilla Location Service**, **Deja Vu Location Service**, and **Apple Wi-Fi** as my backends. The same as when I used 14.1

Checking `/system/priv-app/`. GmsCore is definitely there, with 644 permissions. Automatically installed and set from the fork.

![UnifiedNlp](https://i.imgur.com/xCqF1jX.png)

**Comment by realmain** [comment]
Closing. Dup of #149

**Comment by bam80** [comment]
@realmain, this issue seems common for Android 8.1, and is not specific for Lineage for microG.
E.g., it occurs on Carbon ROM, as [I mentioned](https://github.com/microg/android_packages_apps_UnifiedNlp/issues/149#issuecomment-372146748)

**Comment by gaviidae** [comment]
Hi, I flashed Lineage OS 15.1 and no installation method for UnifiedNlp I know of works. I tried the official version and even compiled one with the build variant eng to get adb root working. UnifiedNlp always shows as not registered in system when on Lineage OS 14.1 the same installation method (push to/system/priv-app/) always worked. I also tried Lineage OS microG as realmain did.
UnifiedNlp also gives me notice that it is not compatible to this version of android. Are there Oreo Roms on which UnifiedNlp works (without GApps)?

**Comment by gaviidae** [comment]
I also applied the [patch](https://github.com/microg/android_packages_apps_UnifiedNlp/blob/master/patches/android_frameworks_base-N.patch) and tried UnifiedNlp as user app, which worked well on Lineage OS 14.1 but didn't on 15.1.

**Comment by realmain** [comment]
Newest Lineage for microG (03/19) for the OnePlus 3T fixed this issue. Closing.

**Comment by bam80** [comment]
@realmain what was the Lineage for microG version with the problem? Were others ticks in Self-Check set there?

**Comment by realmain** [comment]
@wryun unfortunately I do not.

@bam80 It was Lineage for microG 15.1 for OnePlus 3T, ver 03/12/18 and before. All other ticks were checked. The only ones that were not checked was the one in the image in the original post.
