### ISSUE TITLE
Inaccurate Location data.

### ISSUE THREAD

**Issue by kmacod** [microg/android_packages_apps_UnifiedNlp#155]
Problem : 
Map application shows an inaccuracy of over 300KM from my actual location when I use the Mozilla UnifiedNlp where as on the stock ROM, the inaccuracy is just around 20 M .

Here are my specs : 
Phone : Lenovo P2 (p2a42) 
ROM : LineageOS 14.1 with MicroG installed.

I know there is many variable here but I want to determine if it is the UnifiedNlp's fault or the Lineage ROM.

**Comment by n76** [comment]
Most likely it is the Mozilla backend giving bad data. You can use the [SatStat app](https://f-droid.org/packages/com.vonglasow.michael.satstat/) to see both the network based location from the Mozilla backend (passed through UnifiedNlp) and the GPS location. And you can use logcat to see what UnifiedNlp is reporting (location, backend that supplied it, etc.).

You may find that there is a ROM issue with your GPS that is making things worse, but if the Mozilla servers have good data for your area then your position report should be much closer than 300km.

In theory, you can use the [Moxilla stumbler](https://f-droid.org/packages/org.mozilla.mozstumbler/) to map the mobile and WLAN signals in your area to improve the location computation used by the Mozilla backend. You may want to consider doing that. My impression is that Mozilla's data is fairly good in urban and suburban areas but degrades a bit in more rural areas.

I don't normally use the Mozilla backend and I've not found an issue with the UnifiedNlp processing in my use. My current setup is also LineageOS 14.1 with microG installed but the phone make and model are different.
