### ISSUE TITLE
NetworkLocation.apk actually can run as user app !

### ISSUE THREAD

**Issue by aelmahmoudy** [microg/android_packages_apps_UnifiedNlp#16]
Hello,

  Someone told me about this on #fdroid, and I just tried it out now on my OMNI 4.4.4 with today's NetworkLocation v1.1.2 release. I installed NetworkLocation.apk as a user app. (adb install -r /path/to/downloaded/NetworkLocation.apk)

I tried it with @n76's GSM backend, and it actually worked.

I hope you would add in the README that it can be installed as a user app. in some cases, or correct me if I am wrong.

Thanks for today's release btw ;)

**Comment by mar-v-in** [comment]
Yes you're right, most android 4.4/5.0 custom roms support NetworkLocation to be an user app, but some do not (this can be specified at build-time). Not sure how to reflect this in README...
