### ISSUE TITLE
Can't build NetworkLocation

### ISSUE THREAD

**Issue by aelmahmoudy** [microg/android_packages_apps_UnifiedNlp#17]
Hello,

  I was trying to build NetworkLocation for F-Droid project. I was targetting android-19, and I got this error:
```
res/values/themes.xml:6: error: Error retrieving parent for item: No resource found that matches the given name 'Theme.AppCompat'.
res/values/themes.xml:8: error: Error: No resource found that matches the given name: attr 'colorPrimary'.
res/values/themes.xml:9: error: Error: No resource found that matches the given name: attr 'colorPrimaryDark'.
res/values/themes.xml:11: error: Error: No resource found that matches the given name: attr 'windowActionBar'.
```
Is there some library I need to add ?

**Comment by mar-v-in** [comment]
NetworkLocation now uses support-v4 and support-v7-appcompat in their latest release (21?). 

I guess you'll have other build problems as well for the internal android parts used. If you can wait for some hours, i'll upload everything needed to build in this repo (i'll add support for gradle or maven)

**Comment by aelmahmoudy** [comment]
Alright, before seeing your comment, I did a search, and found that I needed to add appcompat v7, so the errors got reduced to:
```
res/values/themes.xml:8: error: Error: No resource found that matches the given name: attr 'colorPrimary'.
res/values/themes.xml:9: error: Error: No resource found that matches the given name: attr 'colorPrimaryDark'.
```

**Comment by mar-v-in** [comment]
I uploaded everything needed to build using gradle with the latest commit, can you just check if it's working fine for you as well?

**Comment by aelmahmoudy** [comment]
Yes, that worked. Thanks !
