### ISSUE TITLE
GSMLocationBackend high CPU usage when location is OFF

### ISSUE THREAD

**Issue by FoxyBee** [microg/android_packages_apps_UnifiedNlp#21]
I notice that the GSMLocationBackend process (org.gfd.gsmlocation) is taking up too much CPU time when the Android location setting is turned OFF. On my Nexus 5, OS Monitor indicates CPU usage constantly fluctuating between (0.0 - 0.5%). It should really be sleeping and using 0 CPU when location is turned off. When sorting by CPU time, it's the 6'th highest process.

**Comment by mar-v-in** [comment]
Does this happen with other backends as well? If not, I guess this is a problem with the third-party backend. It might be related to rtreffer/LocalGSMLocationProvider#8. Please report there.

**Comment by n76** [comment]
I based my local GMS backend https://github.com/n76/Local-GSM-Backend on rtreffer's and I changed a lot so I can't remember if one of my inherited "features" was this or not: In my backend the location is acquired/stored every time there is a change reported in connectivity, so basically the back end is running all the time.

I plan on modifying mine to only run when location requests from the UnifiedNLP are received which should resolve this issue on mine but other backends will need their own changes.

**Comment by FoxyBee** [comment]
I have the following GSM backends installed (downloaded from FDroid): 
1. org.gfd.gsmlocation (CPU time = 01:06, STime=2,315, UTime=4,354)
2. org.fitchfamily.android.gsmlocation (CPU time = 00:02, STime=152, UTime=133)
3. org.microg.nlp.backend.nominatim (CPU time = 00:01, STime=109, UTime=13)

As you can see, it looks like only the first one has the high CPU usage. I'm a little confused as to which github repo "org.gfd.gsmlocation" would correspond to.

**Comment by mar-v-in** [comment]
Partly fixed with #23 , everything else should be rtreffer/LocalGSMLocationProvider#8
