### ISSUE TITLE
Could UnifiedNlp.apk be also present at F-droid?

### ISSUE THREAD

**Issue by bungabunga** [microg/android_packages_apps_UnifiedNlp#25]
i can only use this version because i have google version also present on my sistem. i use an xposed module so that your app could work instead of google's.

thanks!

**Comment by aelmahmoudy** [comment]
I think it can be done.

I will need help with the summary/description of that package & the other one so that users won't get confused when they see two of them.

**Comment by mar-v-in** [comment]
I just read through your description as added to the F-Droid repo. I guess it's better to put the "To be able to use this package, you will either need the" paragraph before the backend list, so it's more likely for users to see it. And you can remove the "WARNING: Depending on your hard-/software configuration" paragraph. I think you can also change the title to something like "UnifiedNlp (Xposed version)", as this is the only real use case right now (although your description is technically right).

As an interesting side-note: I plan to integrate the Xposed module into the UnifiedNlp.apk version longterm, so no additional apk is needed.
