### ISSUE TITLE
f-droid version doesn't work out of the box on CM12

### ISSUE THREAD

**Issue by Susurrus** [microg/android_packages_apps_UnifiedNlp#26]
I have no gapps installed and multiple restarts have done nothing. The README also doesn't provide any guidance on correcting this. Since I didn't download the apk directly I don't know 1) where the apk resides to move it to /system/priv-apps and 2) if doing so will continue to allow it to be updated by f-droid.

I'd really like to use f-droid to keep this updated and to also get this working for my friends.

**Comment by aelmahmoudy** [comment]
did you install any backends ?

**Comment by Susurrus** [comment]
Yes, I've been working with @n76's Cell backend and the Local Wifi backend. We were originally debugging why I couldn't download and use the databases for the cell backend, but I think the issue is that this package isn't working correctly.

I can look at the logs with logcat, but I don't know what this app logs things as. What should I search for so I can verify that it's working?

Additionally, today I decided to reinstall the app. I had carried this app over from my CM11 install to CM12, and things may have changed in that jump. Once I did this and restarted I found the `gsm-backend` tag in the log, but it doesn't do that anymore when I try to use my Battery Saving location finding. In fact I don't see anything related to location stuff at all in the log when doing it.

**Comment by mar-v-in** [comment]
Can you please try if it works with LocalGSMLocationProvider by @rtreffer - it's code works on more devices but is bit battery hungry on others.
You might also want to try the new Mozilla Ichnaea backend. A future version of UnifiedNlp will contain a sophisticated self-test, but this is still in progress.

**Comment by mar-v-in** [comment]
Assuming this is no longer an open issue. In case I am wrong, reopen + comment.
