### ISSUE TITLE
android_frameworks_base-N.patch usable with LineageOS 21 (Android 14)?

### ISSUE THREAD

**Issue by Espionage724** [microg/android_packages_apps_UnifiedNlp#266]
- https://github.com/microg/UnifiedNlp/blob/master/patches/android_frameworks_base-N.patch

[I'm working on getting LineageOS 21 compiled](https://wiki.realmofespionage.xyz/projects:oneplus6_enchilada_lineageos_21), and the old command I had for that frameworks patch years ago gives an error (I'm thinking the command flags changed but I'll look at it more carefully later).

Command:

```
wget -O ~/'Downloads/UnifiedNlp-android_frameworks_base-N.patch' 'https://raw.githubusercontent.com/microg/android_packages_apps_UnifiedNlp/master/patches/android_frameworks_base-N.patch' && cd ~/'android/lineage-21.0' && patch --no-backup-if-mismatch --strip='1' --directory='frameworks/base' < ~/'Downloads/UnifiedNlp-android_frameworks_base-N.patch'
```

Error:

```
can't find file to patch at input line 11
Perhaps you used the wrong -p or --strip option?
```

I saw https://github.com/microg/UnifiedNlp/pull/256 though which has me wondering if that patch is still usable or needed?

**Comment by Espionage724** [comment]
I read https://github.com/microg/GmsCore/wiki/Signature-Spoofing a bit more carefully and noticed the very bottom has a link to up-to-date patches for LOS 21 https://github.com/lineageos4microg/docker-lineage-cicd/tree/master/src/signature_spoofing_patches

**Comment by ghost** [comment]
@Espionage724 btw lineageos sources already patched for microg
https://review.lineageos.org/c/LineageOS/android_frameworks_base/+/383573

**Comment by Espionage724** [comment]
> @Espionage724 btw lineageos sources already patched for microg https://review.lineageos.org/c/LineageOS/android_frameworks_base/+/383573

Thanks, I forgot about that. I was interested in trying to get Location to work without having microG in /system/priv-app (is that still required with the official sig spoof support on LOS?) and thought there might be a patch for that.
