### ISSUE TITLE
How to get the most out of UnifiedNlp

### ISSUE THREAD

**Issue by paulkreuzer** [microg/android_packages_apps_UnifiedNlp#28]
Hi,
I have no basic understanding of software developement and computer science but after thorougly reading the README I got the UnifiedNlp to work perfectly on my Fairphone 1U (Fairphone OS 1.8.2 beta).
I just have a few questions:
1.) I have the GSM Location Backend, Personal Wifi Backend, GSMNetworkLocationProvider and Ichnea Backend installed for Geolocation. Does it make sense to have that many backends? For example the GSM Location Backend allready uses MLS, so the Ichnea Backend is probably redundant right? (To contribute to MLS I use Mozilla Stumbler)

2.) Other Backends like the AppleWifiNLPBackend have antifeatures on F-Droid. ("This app tracks and reports your activity." "This App promotes non-free Network Services.") Does it really send data to Apple?

3.) How does the Nomatim Backend work? 

Greetings,
Paul

**Comment by LuccoJ** [comment]
Let me answer point 2: the Apple backend has to send (potentially sensitive) data to Apple, as that's the only way it can obtain location data from Apple servers. This is true of every backend that works "online": they must send a list of WiFi APs or GSM cells to the server, ask "what location corresponds to these?", and believe the server's answer; in practice, this means letting the server know where you are.

**Comment by paulkreuzer** [comment]
thanks @LuccoJ 
so that means the AppleBackend, like the Ichnea Backend not only uses the database but also contributes to it, am I understanding this right?
Since I'm using UnifiedNlp to NOT send my Data to Google and Apple is no better I won't install it then.

**Comment by LuccoJ** [comment]
@paulkreuzer you aren't contributing back. You are simply making queries to them, while contributing back would mean also giving them your GPS location when GPS is on. It's just that even just making such queries means, by definition, that you are telling them "I am in the location where there is WiFi access point X, and GSM cell Y... can you tell me where that is?".

The Ichnea backend can also optionally contribute data back, but the Apple backend doesn't to the best of my knowledge.

**Comment by paulkreuzer** [comment]
oh ok thanks. :)

**Comment by n76** [comment]
Results from different backends will vary due to different algorithms and databases, my personal feeling is that only one backend for each type of data is needed. That is one backend that locates based on cell/mobile tower information and one that locates based on WiFi AP. Or, if you have a single backend that uses both cell/mobile tower and WiFi AP information that would be sufficient.

It shouldn't hurt to have more than one backend per type of data, just not necessary. If they are based on querying an external server then you'd have more data traffic (and for the privacy minded, more server operators aware of your location). If they are based on using on-phone databases, then more storage used for those databases. So one of each type of backend works for me.

**Comment by paulkreuzer** [comment]
thanks, that sounds reasonable

**Comment by valorize** [comment]
Hi, I tried to find a recommendation for the different Backends. Can you provide one?

**Comment by n76** [comment]
Recommendations for the different backends is probably best discussed on either the [UnifiedNLP](http://forum.xda-developers.com/android/apps-games/app-g-unifiednlp-floss-wi-fi-cell-tower-t2991544) or [MicroG](http://forum.xda-developers.com/android/apps-games/app-microg-gmscore-floss-play-services-t3217616) discussion boards. I am a bit prejudiced as I use the backends that I wrote.

**Comment by gdt** [comment]
I think it would be useful to have discussion on a wiki associated with this project.   @n76 perhaps didn't want to say this, but I think his Local Wifi backend is very useful, and more useful than people who haven't tried it would expect.   I often have osmand using the GPS while navigating, and that results in recording the wifis along the way and where I arrive.  Then, when starting up osmand again, I immediately get location from those same wifis.  The other way it's really useful is if I drive/walk around a building with the GPS on before going inside.  Then I get rudimentary indoor location.  And, this backend does not tell the network where I am.  So while the various ones that use offline full-ish databases of cell/wifi are good, localwifi is in my view the most underrated.

**Comment by ArchangeGabriel** [comment]
I can also recommend @n76 backends, they are very effective and local above all. :)

**Comment by LuccoJ** [comment]
I think I wouldn't mind if the Local WiFi backend also did the same thing it does with WiFi but with GSM cells. I realize it's more feasible to just download a full GSM database beforehand, but still, it wouldn't hurt.

**Comment by ArchangeGabriel** [comment]
Well the idea is that GSM cells are not much susceptible to move, and even often have to be declared to governments and their locations can be pulled from such DB. So not sure if the Local WiFi backend mode would be very useful for GSM cells. Maybe when one travels to another country?

**Comment by n76** [comment]
Might want to move discussion on feature changes to the LocalWiFi backend to its GitHub page. FWIW, adding support for other detected RF sources like mobile towers is something I've thought about and will likely do. My issue at present is I have no time to work on any but the most egregious bugs for the foreseeable future.

**Comment by IzzySoft** [comment]
@ArchangeGabriel not sure if you're right about those GSM cells not much moving. In my experience, they move too much (at least when I check my Tasker profile based on "cell near" and see there must have been ~50 cells next to my door). AFAIK the newest cells (with the latest technology) are first installed in big cities, with their predecessors getting moved to "areas of lower priority" (suburban, villages) until being sorted out "at the lower end".

@n76 you're probably right about moving this out of here and towards your corresponding backends. A hint, though: I use TowerCollector to support OpenCellID with "fresh data". TowerCollector says it also supports informing other apps about its finds. I didn't dig into that, but maybe your LocalGSMProvider could register a listener to that, and update its database "on the fly" then ;)

**Comment by ale5000-git** [comment]
@n76: I haven't yet tried your backends but I have intention to try them.

What is the current status of translations? In particular Italian.
I can help if needed.

**Comment by ArchangeGabriel** [comment]
@IzzySoft Never thought of that possibility, that’s very interesting.

**Comment by IzzySoft** [comment]
@ArchangeGabriel That's probably also one of the reasons for "sudden jumps" (where your location is suddenly "off the tracks"): a moved cell usually causes this within the local region. Some guy moved in with his WiFi router from "down under" or "across the sea" causes a larger jump: from Berlin to New York and back within 10s :smile_cat:

**Comment by n76** [comment]
@ale5000-git - Code is on github, pull requests, including those with translations, are accepted.

https://github.com/n76/Local-GSM-Backend
https://github.com/n76/wifi_backend
