### ISSUE TITLE
Adding Unwired Labs Geolocation API to Nlp

### ISSUE THREAD

**Issue by gopi-ar** [microg/android_packages_apps_UnifiedNlp#30]
Hi,

I'm a founder at Unwired Labs (https://unwiredlabs.com), and we offer a Geolocation service as an alternative to Google. We take privacy pretty seriously and want to offer this free of charge to power users.

How do we integrate our API as an option to the Unified Nlp? 

Cheers,
Gopi

**Comment by mar-v-in** [comment]
The UnifiedNlp API is described and provided [here](https://github.com/microg/android_external_UnifiedNlpApi), allowing you to develop and add custom backends to UnifiedNlp. Usage of `org.microg.nlp.api.HelperLocationBackendService` together with `org.microg.nlp.api.CellBackendHelper` might coding work (see [Ichnaea implementation](https://github.com/microg/IchnaeaNlpBackend/blob/master/src/org/microg/nlp/backend/ichnaea/BackendService.java) for usage, documentation is not yet fully done for these helpers as they just got added recently)

**Comment by mar-v-in** [comment]
I am closing here. If you need additional information or implementation support, feel free to re-open or mail me at microg at larma.de
