### ISSUE TITLE
tag apps properly

### ISSUE THREAD

**Issue by KOLANICH** [microg/android_packages_apps_UnifiedNlp#32]
Tag apps properly with [antifeature](https://f-droid.org/wiki/page/Antifeatures) tags. For example, most of providers should be tagged with "tracking" antifeature.

**Comment by aelmahmoudy** [comment]
I think that should be done with online providers.

**Comment by KOLANICH** [comment]
I meant this. But I don't mind that we need an own issue for each.

**Comment by mar-v-in** [comment]
I am unsure about the usage of the tracking anti-feature. Nearly every app using an online service can be tagged with it, as the server might have tracking. However sometimes one can assume that tracking is not done (eg. server software is open source), but can't guarantee. In other cases, the data send to the server is not really usable for tracking.

Giving an example: The apple servers (used by the nlp backend) might do tracking, but requests do not contain any IDs that might be used for this and the submitted data can not even be used to build up a location database (other than the mozilla service). The Mozilla service makes building up the location database optional and we can check that be looking at the server source, however there is no guarantee that the source code on github is the one used on their servers. 

This makes the tracking anti-feature more or less useless to me, especially most tracking systems use proprietary servers, so the proprietary server tag will be enough...

**Comment by KOLANICH** [comment]
>but requests do not contain any IDs
They contain ip so they can be binded into group. Further it is enough to have 3 feature points to identify men.
http://www.nature.com/srep/2013/130325/srep01376/full/srep01376.html

>Nearly every app using an online service can be tagged with it, as the server might have tracking.
It depends on app functionality.

**Comment by KOLANICH** [comment]
the packages are still not tagged

**Comment by mar-v-in** [comment]
Do I understand you right that you mean the antifeature tags displayed in F-Droid? If yes, please report this directly to F-Droid at https://gitlab.com/fdroid/fdroiddata/issues
If you meant something else, please elaborate.
