### ISSUE TITLE
μg UnifiedNLP for GAPPS via F-Droid: cannot update

### ISSUE THREAD

**Issue by equaeghe** [microg/android_packages_apps_UnifiedNlp#37]
This may be an F-Droid issue, let me know then.

F-Droid propmts me that a new version of μg UnifiedNLP for GAPPS is available. I currently have 1.1.08 and 1.3.0 is offered. When I try to update, it informs me that the new versions is signed with a different key and must be deleted first. When I try to delete it, I get a de-installation error. I thought that for some reason I may have made a system app out of it, but when I look for it with the /syste/app mover, I don't find it.

What may be the issue here?

**Comment by equaeghe** [comment]
Update: it seems that the delete operation wants to delete the network location app, which is a system app. Is it correct that this is one and the same as μg UnifiedNLP for GAPPS? It rather looks like an app included with my phone (Xperia U w/Android 4.0.4).

**Comment by mar-v-in** [comment]
There never was a version 1.1.08 of µg UnifiedNlp.

The "µg UnifiedNlp for GAPPS-free devices (legacy)" package on F-Droid uses the package name "com.google.android.location" that is used for network location on Android versions before 4.4. As you have another network location provider (by google) installed on your device, µg UnifiedNlp is displayed as an update, but it is not, it's a different piece of software that uses the same package name.

In F-Droid, you can choose to ignore updates for this app (menu->ignore all updates), as you'll not be able to use them.

If you want to use µg UnifiedNlp on your phone (if rooted), remove /system/app/NetworkLocation.apk, download "µg UnifiedNlp for GAPPS-free devices (legacy)" from F-Droid and move it to /system/app

**Comment by KAMiKAZOW** [comment]
@mar-v-in Maybe you should close this issue.
