### ISSUE TITLE
Position known in logcat, but not for apps

### ISSUE THREAD

**Issue by utack** [microg/android_packages_apps_UnifiedNlp#40]
Hi,

without GPS location it often happens that the position is known in logcat, but not to apps.

Logcat example, when the app does not know the location:
```
V/NlpLocationBackendFuser(18127): location=Location[network 48.732133,11.180442 acc=1090 et=+2d9h24m35s23ms {Bundle[{noGPSLocation=Location[network 48.732133,11.180442 acc=1090 et=+2d9h24m35s23ms {Bundle[{AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GSMService}]}], AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GSMService}]}]
```
The sitation varies, and after waiting for a while the position is sometimes known in the app again
Logcat example when the app currently does know the location:
```
V/NlpLocationBackendFuser(18127): location=Location[network 48.732758,11.180404 acc=799 et=+2d9h30m48s403ms {Bundle[{noGPSLocation=Location[network 48.732758,11.180404 acc=799 et=+2d9h30m48s403ms {Bundle[{AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GSMService}]}], AVERAGED_OF=1, SERVICE_BACKEND_PROVIDER=gsm, SERVICE_BACKEND_COMPONENT=org.fitchfamily.android.gsmlocation/.GSMService}]}]
```

CM12.1(Android 5.1) nightly builds from end of March to mid May
UnifiedNlp for Gapps free devices 1.3.0
LocalGsmNlpBackend 0.7.0 with different builds of OpenCellID/Mozilla databases.
Google Maps or OsmAnd as apps using the location.

Hopefully you can find an easy solution, it is really annoying when apps don't know the location quite often.
Let me know if you need more information or need me to run a debug build of the apps with more logcat activity.

**Comment by utack** [comment]
I have not ovserved this again, it can be closed.
No idea what solved it.

**Comment by Iey4iej3** [comment]
The apps know the location only after several log messages like this `NlpLocationBackendFuser...location=Location[network ...]`. Is this expected? @mar-v-in
