### ISSUE TITLE
Migrate from the "old NOGAPPS"

### ISSUE THREAD

**Issue by IzzySoft** [microg/android_packages_apps_UnifiedNlp#41]
I have a device where, when I last flashed it, I installed NetworkLocation from NOGAPPS. Is there a recommended migration path to switch to µg, so I can use additional backends? It's of course a device with no GApps on (CyanogenMod with Android 4.3), having them replaced by all the NOGAPPS components (MapsAPI, BlankStore, NetworkLocation).

**Comment by mar-v-in** [comment]
There is no way to migrate your wifi cache database. If you used lacells.db with NOGAPPS NetworkLocation, you can continue to use it via the LocalGsmNlpBackend. 

The UnifiedNlp build I published here on GitHub is signed using the nogapps key, meaning you can seemlessly upgrade to UnifiedNlp without the need to modify /system partition. If you want to receive updated from F-Droid, you need to download their latest release and replace NOGAPPS NetworkLocation with it.

**Comment by IzzySoft** [comment]
Thanks a lot, @mar-v-in – the second paragraph was what I'm after (no need for data migration, as I currently only use the `lacells.db`). I'll try with the Github version then, and report back.

Speaking of F-Droid and the "key replacement" (as F-Droid builds from sources using their own key): Would you consider using an [own F-Droid Repo](http://android.izzysoft.de/articles/named/list-of-fdroid-repos)? Just asking as that would speed up new releases being available via the F-Droid app (the few people with signature issues on switch from NOGAPPS certainly wouldn't justify that *now*, just because I'm late on this train).

**Comment by phalTowers** [comment]
"There is no way to migrate your wifi cache database"

Titanium Backup  (pro) did for when when I switched phones.

**Comment by phalTowers** [comment]
for when when == for me when

**Comment by mar-v-in** [comment]
@phalTowers migrating data cross-device with the same version does work of course, but this is about cross-version (nogapps nlp vs µg unifiednlp)

@IzzySoft just realized your open question here: You don't need UnifiedNlp.apk when using (Legacy)NetworkLocation.apk

**Comment by IzzySoft** [comment]
Thanks, @mar-v-in – good to know. Meanwhile guessed as much from [this issue](https://github.com/Rawi01/XposedUnifiedNlp/issues/2) on the Xposed module, which shed some light. Unfortunately, I still didn't get UnifiedNLP working on my stock-ROM LG P880 (same as the two reporting over there) – but that's a different issue.
