### ISSUE TITLE
[solved] Can't uninstall / reinstall UnifiedNlp

### ISSUE THREAD

**Issue by herrdeh** [microg/android_packages_apps_UnifiedNlp#45]
I already had it, but cant find the solution again...embarassing... ):

I installed the wrong UnifiedNlp package ("with GAPS"), uninstalled it again, now tried to install the GAPPS-free flavour on F-Droid, but  F-Droid keeps saying "You are trying to install a prior version of an already installed app". I dont find anything in /system/apps, nor in /system/priv-apps, and a search for "nlp" doesnt give me results.

What can I do?

**Comment by IzzySoft** [comment]
Have you checked in *Settings › Apps*? If not found there, additional options to "remove left-overs" include:

* using `adb shell pm clear org.microg.nlp` to clear potentially left data
* using `adb uninstall org.microg.nlp` to force-uninstall again
* trying an app like [SD Maid](http://www.appbrain.com/app/sd-maid-system-cleaning-tool/eu.thedarken.sdm) (which has a "CorpseFinder")

Having cleaned up, try installing UnifiedNlp again.

Note: My examples are for a specific package. You might have to adjust the package name if you've used a different one.

**Comment by mar-v-in** [comment]
In Settings > Apps make sure to check at the bottom of the list. It might happen that the app is installed for a "different user" (even if you're the only user on the phone). If that's the case you can open the menu while on the settings of the app and select "Uninstall for all users" (or sth. alike)

**Comment by herrdeh** [comment]
SD maid fails, settings > apps doesnt find anything.
The given adb commands do fail as well. So - sorry, I'm not smart enough which are potential other package names. Could you please provide them? Thx!

**Comment by herrdeh** [comment]
Even after updating the system from Kitkat to Lollipop (SlimKat -> SlimLP), I still cannot install UnifiedNlp for the given reasons. )))))o:

**Comment by herrdeh** [comment]
Dah!
I still had g**gle play services installed, but hibernated by TitaniumBackup. This interfered with UnifiedNlp. Uninstalling play services did it.

Strange enough:
In F-Droid, for UnifiedNlp version number 7.5** was displayed.

So: 
Happy again... (-;
