### ISSUE TITLE
I'd this project still alive? Or all efforts go to GmsCore?

### ISSUE THREAD

**Issue by timofonic** [microg/android_packages_apps_UnifiedNlp#49]
Hello.

I would like to know if this project is still alive it all efforts are going to GmsCore to provide an integral solution.

Since UnifiedNlp providers are not so updated and all them are in external repositories. Why not making them part of MicroG project and maintain them?

Kind regards.

**Comment by mar-v-in** [comment]
This project is mostly finished as it runs smoothly on latest Android versions without GAPPS. As GmsCore in fact uses the code in this repository, it will also be updated once needed.

Regarding backends: Some backends run fairly well, I personally use [LocalGsmNlpBackend](https://f-droid.org/repository/browse/?fdfilter=Mozilla&fdid=org.fitchfamily.android.gsmlocation) for GSM based location and [MozillaNlpBackend](https://f-droid.org/repository/browse/?fdfilter=Mozilla&fdid=org.microg.nlp.backend.ichnaea) for Wi-Fi based location. Additionally the Apple backend runs fine as well, but is using Apple Servers...

**Comment by krt16s** [comment]
@mar-v-in Since some flavors use Google's gms namespace which is used by GmsCore as well, would you recommend switching them over (in time)? Will GmsCore work as drop-in replacement?

**Comment by mar-v-in** [comment]
I will continue to provide builds of UnifiedNlp in the gms namespace flavor. UnifiedNlp fulfills a different need than GmsCore. A lot of people are not interested in any feature provided by GmsCore and/or can't use it as it requires a patch to the system. Additionally, the APIs used to contact UnifiedNlp are open source, which means that free software as found on F-Droid uses them, while Play Services APIs are (currently) only used in non-free apps (although they might be open-source). I consider applications that include proprietary libraries non-free, this includes popular open-source apps like TextSecure/Signal.

GmsCore can be used as drop-in replacement when replacing my UnifiedNlp release build with my GmsCore release build. For other build options (F-Droid UnifiedNlp or GmsCore nightly) you will need to uninstall UnifiedNlp first, then install GmsCore and finally activate the backends.

**Comment by Gitoffthelawn** [comment]
Is there a good primer for UnifiedNlp and GmsCore, including the different layers?

**Comment by krt16s** [comment]
Right now we at fdroid can only build one (since our build system is build around unique package ids), either UnifiedNlp (at least the flavor reusing googles id) or GmsCore. We could switch that flavour to build GmsCore instead (and making that clear in the description and by using special versionnames). In case of another UnifiedNlp release, we can switch back for one build, wait until it is published and then return to build GmsCore. We most likely need to apply some version-code magic as well... 

I am not to fond of maintaining two apps in the same metadata file, though. Maybe @mvdan has an idea...

**Comment by mvdan** [comment]
We already have instances of apps spanning over multiple metadata files, e.g. when an app has plugins.

**Comment by mar-v-in** [comment]
I guess it should not be too hard to provide both builds through F-Droid. The problem right now is that the GmsCore repo contains binaries of third party library. I will fix this soon(tm), maybe with the v0.02 release. Unfortunately CM denied to include the signature faking feature, thus GmsCore will not be usable for majority of "non-expert" users making F-Droid support rather low priority for me...

**Comment by krt16s** [comment]
@mvdan is was talking about two apps having the same package id, not signature.

**Comment by mvdan** [comment]
I also think having two separate apps in the same package id would be confusing. If one replaces the other, then good. If not, and they must both stay, it will be messy.

**Comment by IzzySoft** [comment]
@mvdan unfortunately in this case, both are intended to replace a 3rd candidate – and dependencies require the package name to be identical. Not the usual "every-day-case" where one accidentally forgot to change the package name when copying from a template ;)

**Comment by mvdan** [comment]
I don't think breaking the "one appid is one single app" rule will help with any of this. If anything, it would make F-Droid much more complicated.

**Comment by IzzySoft** [comment]
I agree, @mvdan – running a site which relies on that (see [IzzyOnDroid](https://android.izzysoft.de/)), I had that confusion already with UnifiedNLP suddenly getting all the permissions of its Google counterpart added ;) Not sure how that could be solved – so I better "shut up" now.

**Comment by herrdeh** [comment]
I found the NOGAPPS project on xda. Is that going to be the successor of UnifiedNlp?

Tried to install "NetworkLocation" from there, but installation failed. Do I have to uninstall UnifiedNlp first?

**Comment by breversa** [comment]
Izzy wrote about your question on his blog. Check it out, it's full of Google-free goodness : https://android.izzysoft.de/articles/named/android-without-google-5a :-)

**Comment by LuccoJ** [comment]
@herrdeh NOGAPPS is an older name, actually. microG is the newer name for the whole bundle. If you don't need the entire microG, my advice is to just install unifiedNLP and its backends through F-Droid: that way they're kept up-to-date.

**Comment by IzzySoft** [comment]
@LuccoJ backends need to be installed from F-Droid anyway (they're not part of "the core"). Btw, @breversa : thanks to a little exchange on issues (I guess it was @herrdeh I had this with?), that article just got some minor updates ;)

**Comment by LuccoJ** [comment]
They can be installed from their APKs or compiled from source, they don't HAVE to be installed from F-Droid. It's just quite convenient, just as with unifiedNLP itself.
