### ISSUE TITLE
What's UnifiedNlp.apk for ?

### ISSUE THREAD

**Issue by aelmahmoudy** [microg/android_packages_apps_UnifiedNlp#6]
Hello,

  There's a UnifiedNlp.apk in the release, what is it for ? I don't see any mention of it in the README except in the Building section.

**Comment by aelmahmoudy** [comment]
What config needs to be changed to make this one running ? Do you think it is done already on custom ROMs like OMNI & CM ?

**Comment by mar-v-in** [comment]
It requires `org.microg.nlp` to be added to the list of network location services. This is not done for any ROM yet. Most (up to all) have `com.google.android.gms` (NetworkLocation) and omni additionally supports `com.google.android.location` (LegacyNetworkLocation). As the number of services there should be kept small (to not open an attack vector), I guess it's good not to add everything there.

And I'm quiet sure that Google will forbid CM to put something else than their service into this build config...

**Comment by breversa** [comment]
UnifiedNlp.apk is used by XposedUnifiedNlp (https://github.com/Rawi01/XposedUnifiedNlp) to be able to use Unified NLP even if GApps are installed. :-)
