### ISSUE TITLE
unable to uninstall from nexus 6

### ISSUE THREAD

**Issue by jacobhilker1** [microg/android_packages_apps_UnifiedNlp#64]
i installed the no gapps version from f-droid on my nexus 6(no root, on marshmallow). when i try to uninstall it from f-droid, i get an error saying "unable to uninstall due to an unknown error." is there any way i can uninstall it without a reset?

**Comment by n76** [comment]
You should be able to uninstall any app installed on /data using the controls in the system settings under apps. At least that is true with all versions of Android I've used but I haven't yet used Marshmallow.

**Comment by jacobhilker1** [comment]
I am not even seeing it show up on the apps list.

**Comment by n76** [comment]
Wild guess: If its not on the apps list then it probably has been uninstalled and the issue might be with the database that F-Droid uses to track what it has installed. I'd be tempted to force stop F-Droid and see if that clears the error.

**Comment by jacobhilker1** [comment]
Didn't clear the error

**Comment by IzzySoft** [comment]
If you can use ADB, please try:

    adb shell "pm list packages -3"

and check if the output includes this line:

    package:com.google.android.gms

(which is the "no GAPPS" version of UnifiedNlp from F-Droid). If so, try `adb uninstall com.google.android.gms` and repeat the above. Did you get any error for the `adb uninstall` command? If not, was the line still there in the second run?

**Comment by jacobhilker1** [comment]
izzy i can't get it to launch on my desktop. when i try to just run it it doesn't stay open, but when i try to run it as an admin, it freezes up and eventually says that it didn't respond to the start. do you have any ideas? my pc specs are a core i5-4640, 8 gb ddr3-1600 mhz ram, 1 tb seagate barracuda 7200 rpm hdd, nvidia gtx 950 and a 500 watt psu all in a cooler master n200. its running windows 10

**Comment by IzzySoft** [comment]
Sorry, I'm not the Windows guy (especially not W10). And I don't know what you mean by "doesn't stay open". You've got the drivers for the Android device installed on W10? Then open a cmd window, `cd` into where `adb.exe` is located, and run `adb devices`: does it show your device? If so, continue with the above. If not, you might have forgotten to enable USB-Debugging in your Android's Developer options. Or the drivers are having issues.

Btw: you could also try with a terminal app (not sure if that would need root then, as ADB has some elevated permissions). In that case, leave off the `adb shell` and make the command `pm list packages -3 | grep com.google.android.gms`, and use `pm uninstall com.google.android.gms`.

**Comment by jacobhilker1** [comment]
sorry for not explaining further izzy,
what i mean by adb not staying open is that it will show up on screen for maybe one or two seconds, and then it will close.

**Comment by jacobhilker1** [comment]
Got it uninstalled with a data clear and force stop. Thanks for trying to help me!

**Comment by jacobhilker1** [comment]
Nope, it actually didn't uninstall, so I guess I try a reinstall of F-Droid and another data clear.

**Comment by jacobhilker1** [comment]
I guess my problem is that I still have the Google services installed as well and I won't be able to uninstall the unified Nlp because I forgot to install both a backend and the Google services version.

**Comment by IzzySoft** [comment]
> I guess my problem is that I still have the Google services installed

and

> i installed the no gapps version

somehow is a contradiction, isn't it? No wonder you're seeing issues not being able to uninstall. It's not [UnifiedNlp](https://f-droid.org/repository/browse/?fdfilter=unifiednlp&fdid=com.google.android.gms) you're seeing installed, but rather the [Google package using the very same package name](https://developers.google.com/android/reference/com/google/android/gms/package-summary) (both use `com.google.android.gms`). I wonder how you were able to *install* UnifiedNlp from F-Droid at all.
