### ISSUE TITLE
[Feature Request] Support for non-unified NLP

### ISSUE THREAD

**Issue by xuefer** [microg/android_packages_apps_UnifiedNlp#67]
UnifiedNlp should list and support for pre-UnifiedNlp network location providers, like gms, AMAPNetworkLocation, BaiduNetworkLocation. etc. these NLP is supported and used by original system, although only 1 of them is used. they works without any configuration. UnifiedNlp should be able to use them like UnifiedNlp-providers. supporting to post-kk (4.4 ~ ) is enough

**Comment by rerbin** [comment]
Yes,it's very useful.

**Comment by mar-v-in** [comment]
It should be possible to build a UnifiedNlp backend around these providers. I don't think that support for proprietary third party software should be backed into UnifiedNlp.
