### ISSUE TITLE
“Address lookup" have no options

### ISSUE THREAD

**Issue by rerbin** [microg/android_packages_apps_UnifiedNlp#71]
![screenshot_20160309-124338](https://cloud.githubusercontent.com/assets/17610552/13625705/5e35271e-e5f5-11e5-875c-eedfef86a9ec.png)

**Comment by n76** [comment]
Have you installed a backend for this? I believe the only one at present is the Nominatim one available from the standard F-Droid repository at the NominatimNlpBackend.

**Comment by rerbin** [comment]
Thanks，i know now。

**Comment by agilob** [comment]
Can be closed.
