### ISSUE TITLE
Revert to plain versioncode in gradle files

### ISSUE THREAD

**Issue by krt16s** [microg/android_packages_apps_UnifiedNlp#78]
Since you switched to generate version and versioncode on build, there is no way to get those information without building it. This breaks updatechecks and auto-update for f-droid. Could you revert to using plain values?

**Comment by mar-v-in** [comment]
It is possible to get the said information without building, it's just not the way F-Droid is currently working.

1. The way version code and name is generated is fully deterministic. F-Droid servers already download the git repo and can thus easily call the required commands (see [here](https://github.com/microg/android_packages_apps_UnifiedNlp/blob/master/unifiednlp-app/build.gradle#L31) and [here](https://github.com/microg/android_packages_apps_UnifiedNlp/blob/master/unifiednlp-app/build.gradle#L40))
2. As you don't want to add a specific system to F-Droid only for UnifiedNlp, this should be done in a "standard" way. 
  - Fortunately you can also ask gradle for the version number of a package without building it (which is way more better than trying to parse the gradle file using regex as it is done currently). [1]
  - It would also be possible to have a script in the repo that will return the required information. 

  However both mean that arbitrary code will be executed, which requires the process to be sandboxed properly (which I am not sure if it is done currently)

In my opinion, this is a bug in F-Droid, as they are not able to correctly handle Gradle-based build process. Trying to parse the build.gradle with regex which will always be incomplete even for plain version code is not the correct way to handle Gradle!

[1] [This script](https://gist.github.com/mar-v-in/280cec64b20a45b4974c) will return the following output when run on current UnifiedNlp master - without actually building it:
```xml
<application xmlns:android="http://schemas.android.com/apk/res/android" project="microg-ui-tools" package="org.microg.tools.ui" android:versionName="v0.1.5" />
<application xmlns:android="http://schemas.android.com/apk/res/android" project="unifiednlp-api" package="org.microg.nlp.api" android:versionName="v1.5.0" />
<application xmlns:android="http://schemas.android.com/apk/res/android" project="unifiednlp-app#LegacyNetworkLocation" package="com.google.android.location" android:versionCode="20150" android:versionName="v1.6.2-8-g1319356" />
<application xmlns:android="http://schemas.android.com/apk/res/android" project="unifiednlp-app#NetworkLocation" package="com.google.android.gms" android:versionCode="20150" android:versionName="v1.6.2-8-g1319356" />
<application xmlns:android="http://schemas.android.com/apk/res/android" project="unifiednlp-app#UnifiedNlp" package="org.microg.nlp" android:versionCode="20150" android:versionName="v1.6.2-8-g1319356" />
<application xmlns:android="http://schemas.android.com/apk/res/android" project="unifiednlp-base" package="org.microg.nlp" android:versionName="v1.6.2-8-g1319356" />
```

**Comment by krt16s** [comment]
I agree, that it's an fdroid issue, but having this done in a general way useful for most gradle builds isn't an easy task. Maybe we need per-app updatecheck-scripts.

@mvdan: Could you have a look at this?

**Comment by mvdan** [comment]
> However both mean that arbitrary code will be executed, which requires the process to be sandboxed properly (which I am not sure if it is done currently)

It is not, which is why we are not running gradle.

> In my opinion, this is a bug in F-Droid, as they are not able to correctly handle Gradle-based build process. Trying to parse the build.gradle with regex which will always be incomplete even for plain version code is not the correct way to handle Gradle!

Of course it isn't. But it's a secure and fast method that doesn't need sandboxing. And right now it works for every app out there that doesn't have an evaluated version name/code, which is 99% of apps out there.

If you want to provide a patch to fdroidserver, feel free to do so. Bear in mind that:

* It should be generic, working on all apps that the current method does
* We fetch version name and code _lots_ of times, I would estimate around 10.000 times daily. For example, we check the last few tags for each git repo using them, and we try each build.gradle that we find. The new mechanism cannot be considerably slower or things will become very painful.

**Comment by mar-v-in** [comment]
> We fetch version name and code lots of times, I would estimate around 10.000 times daily. For example, we check the last few tags for each git repo using them, and we try each build.gradle that we find.

I guess this is the most relevant problem. You don't need to process git tags you already processed before and if you do you're wasting cpu time. Assuming that apps use git and tags, all you need to do is to `git pull` check if there are new release tags (i know there are already means to qualify a tag as release tag) and for each of them open a sandbox (let's say lxc container) and determine the version code at that tag (eg. using the version.gradle script I proposed in my last comment). This will not be 10.000 times daily but probably less than 50 sandboxed gradle invocations per day - no matter how often you pull from git, as apps just don't update that often. And I don't think that adding some execution about 50 times a day will impact performance a lot.

PS: I don't know a lot about how F-Droid server works internally, this was just some basic thoughts.

**Comment by mvdan** [comment]
A lot of assumptions here :) People force-push tags, for example.

Even if you ignore problems like that, as with the gradle thing, someone would need to implement this.

Either way, fetching a version should be quick. Parsing the gradle file and evaluating a name should take no time. Whether gradle spends entire seconds starting up and setting up the project is another thing.

**Comment by mar-v-in** [comment]
You can store commit id for tags to make sure you catch force-pushed tags. Also: what version would you want to have in F-Droid: the one before or after forced push?

**Comment by mvdan** [comment]
> You can store commit id for tags to make sure you catch force-pushed tags.

What if you modify the mechanism to obtain the version name/code then? Do you flush the entire cache? It's not as simple as it might seem, this is my point.

> Also: what version would you want to have in F-Droid: the one before or after forced push?

We currently use whatever is in the repo at the moment, so the new one.

**Comment by mar-v-in** [comment]
> What if you modify the mechanism to obtain the version name/code then? Do you flush the entire cache? It's not as simple as it might seem, this is my point.

The [version.gradle script](https://gist.github.com/mar-v-in/280cec64b20a45b4974c) I linked earlier is able to correctly handle all mechanisms to set the version name/code that work with gradle. It should also properly handle flavors and eg manifest files that are not called AndroidManifest.xml. There is no relevant cache involved in the version name/code retrieval. If you force-push a new version name/code on the same tag, this will result in problems when trying to build later as version does mismatch now, but this is likely to happen with current implementation as well, right?

**Comment by mvdan** [comment]
You said earlier "we would only check each commit once". What I meant is that if that is true, you would have to re-check all the commits if the gradle code we use to fetch the version ever changes.

**Comment by mar-v-in** [comment]
I now work-around this issue using a comment inside the gradle build file that tricks the F-Droid server (see https://github.com/microg/android_packages_apps_UnifiedNlp/blob/master/unifiednlp-app/build.gradle#L28). This way I can have release in F-Droid and nice version strings and automatically increasing version numbers for non-release builds. Works fine with UnifiedNlp and some backends as well.
