### ISSUE TITLE
unifiedNLP (GAPPS) "System supports location provider" is not checked

### ISSUE THREAD

**Issue by mustermaxmueller** [microg/android_packages_apps_UnifiedNlp#79]
im using unifiedNLP (GAPPS) from f-droid (v1.6.2-dirty https://f-droid.org/repository/browse/?fdid=org.microg.nlp)
i added org.microg.nlp to config_locationProviderPackageNames (http://pastebin.com/XiE3L1FA#110) as stated here:
https://f-droid.org/repository/browse/?fdid=org.microg.nlp (second paragraph)

"System supports location provider" and "UnifiedNLP is registered in system" arent checked.

if im using the unifiedNLP xposed module everything is working fine.

am i missing something?

im running sony z ultra on omnirom mm

**Comment by mar-v-in** [comment]
"System supports location provider" will check the actual value of relevant fields in the system. Note that some devices trees include device specific overlays that might set `config_enableNetworkLocationOverlay` to `false`, which will render changing `config_locationProviderPackageNames` useless.

Can you share the resulting /system/framework/framework-res.apk to verify the result of your patch?

**Comment by mustermaxmueller** [comment]
Sorry for the late reply.
here is the frameworks-res.apk:
https://drive.google.com/open?id=0Bydasv21DQbFRjlzU3lDWkM0WXc
if i decompile it `config_enableNetworkLocationOverlay `is set to true.
but under `config_locationProviderPackageNames `there is no entry `<item>org.microg.nlp</item>` :(
so problem is with my build. altough it should be listed (see post #1). but at least now i know where to look for a fix!

thanks

**Comment by mustermaxmueller** [comment]
as im using omnirom i had to edit https://github.com/omnirom/android_vendor_omni/blob/android-6.0/overlay/common/frameworks/base/core/res/res/values/config.xml
and not the xml file in the devicetree (see post 1)
