### ISSUE TITLE
Please add support for Copperhead OS

### ISSUE THREAD

**Issue by christoph-buente** [microg/android_packages_apps_UnifiedNlp#81]
Hi,

i just installed CopperheadOS, a hardened android version for Nexus models. (https://copperhead.co/android/)

But unfortunately the network based location does not work. I can install UnifiedNlp and some backends. But the selfcheck says, my system does not support this package. I also left a comment on the copperhead bug tracker: https://github.com/copperhead/bugtracker/issues/186#issuecomment-200861801

It would be great if both awesome projects could collaborate.

Thx and keep the good work up.

Christoph

**Comment by mar-v-in** [comment]
I answered in the mentioned issue with technical details for Copperhead to add network location provider support. There is nothing else I can do to solve the issue.

**Comment by christoph-buente** [comment]
Thx Marvin, really appreciate it.
