### ISSUE TITLE
OpenWLANMap can never find GPS fix

### ISSUE THREAD

**Issue by vermut** [microg/android_packages_apps_UnifiedNlp#82]
It's starts, no exceptions in logs, initiates GPS connection but even when it's established still "Waiting for GPS fix...". Same with OpenWLANMapMini

[Logs](https://gist.github.com/vermut/7dfe371554ce1b67c43c)

**Comment by mar-v-in** [comment]
UnifiedNlp is not providing GPS data. Applications can request the system to only use GPS location and not Network-based location. Those applications will never receive a location update from UnifiedNlp. And that's what causing the problem with OpenWLANMap here, as it requires GPS fix, not Network-based location.
