### ISSUE TITLE
lost Settings after phone reboot

### ISSUE THREAD

**Issue by Zitronella** [microg/android_packages_apps_UnifiedNlp#83]
I have installed [µg UnifiedNlp (no GAPPS)](https://f-droid.org/repository/browse/?fdfilter=UnifiedNlp&fdid=com.google.android.gms) on my Motorola Moto E 2. Generation with [Cyanogenmod 13 nightly](http://www.cmxlog.com/13/surnia/) ( cm-13.0-20160330-NIGHTLY-surnia.zip) and also installed 
[OpenBmapNlpBackend](https://f-droid.org/repository/browse/?fdid=org.openbmap.unifiedNlp)

In UnifiedNLP Settings i Configure location backends:
-Online/offline mode --> "Offline mode"
-Offline database --> "openbmap"
-Database folder --> /storage/emulated/0/Android/data/org.openbmap.unifiedNlp/files

After reboot the phone the settings are gone and it is
-Online/offline mode --> "Online mode"
-Offline database --> "None"

I am not sure if it is a bug in UnifiedNlp or in CM 13 nightly. Maybe you can help? Sorry for my bad english.

**Comment by mar-v-in** [comment]
I guess this is a bug in OpenBmapNlpBackend. Please report the issue here: https://github.com/wish7code/org.openbmap.unifiedNlpProvider/issues
UnifiedNlp only stores which backends are enabled, not their configuration.
