### ISSUE TITLE
no icon to launch UnifiedNLP if installed under /system/app

### ISSUE THREAD

**Issue by mustermaxmueller** [microg/android_packages_apps_UnifiedNlp#85]
If i move the apk to /system/app or /system/priv-app there is no icon to launch the app in the app drawer.
i want to distribute my rom with UnifiedNLP as a system app because of adding UnifiedNLP to the system location providers and it might be a security issue otherwise.
its also not possible to start the app via android.intent.action.MAIN if the app is installed in the system partition.

**Comment by mar-v-in** [comment]
If UnifiedNlp is installed in the system partition (as part of the ROM), its settings will be accessible from System Settings -> Location

**Comment by mustermaxmueller** [comment]
you are right :)
altough its stated in the wiki (https://f-droid.org/wiki/page/org.microg.nlp) it is not clear that it'll work that way if installed as a system app. maybe update wiki?

nevertheless
thanks alot!
