### ISSUE TITLE
Display color yellowish

### ISSUE THREAD

**Issue by nezirus** [microg/android_packages_apps_UnifiedNlp#89]
After installing µg UnifiedNlp (no GAPPS) v1.6.6 and MozillaNlpBackend v1.3.2 my phone's display changes color temperature to yellowish tint after switching Location services on.

(During reboot color temperature is normal, after disabling Location services and reboot color is also normal)

My device is Moto G 2014 (titan) with Cyanogemod 12.1 (https://download.cyanogenmod.org/get/jenkins/135150/cm-12.1-20151117-SNAPSHOT-YOG7DAO1K5-titan.zip)

**Comment by mar-v-in** [comment]
Seriously? There is no way, that UnifiedNlp has a direct influence to your screen.

I can just guess: Your ROM does some sort of color correction based on estimated environment (sun,night). This is done by using date+time+location. With no location services it won't work.
I am not sure if CM has such a feature, but nonetheless, it's not UnifiedNlp causing the display change, so check with your ROM developer(s).

**Comment by IzzySoft** [comment]
@mar-v-in That's called "Ambient" I guess. Have it here on CyanogenOS 12.1, serves a day and a night mode (the latter is a blue filter AFAIR). One also can adjust those filters. But full ack, I don't think UnifiedNLP triggered that :)

**Comment by ArchangeGabriel** [comment]
The name is “Live Display”. It isn’t supposed to use location AFAIK, but it seems to have strange triggering issues that could be related (like only triggering on certain events rather than just time).

**Comment by IzzySoft** [comment]
@ArchangeGabriel Ah yes, right. I always mess up the two terms (when it comes to light, "ambient" sounds so fitting ;) Now I need to figure what Ambient was …

**Comment by nezirus** [comment]
Thanks guys, it was caused by "Live Display" feature on my ROM, but it was definitely triggered by UnifiedNlp, I've had the same ROM for the last 6 months and never had any issues with screen color temp. I've never touched any of the "Live Display" settings (it was set on "automatic")

**Comment by ArchangeGabriel** [comment]
@IzzySoft Ambient Display is the thing that make you screen blink when they are new notifications to display them on a minimalist black background.
