### ISSUE TITLE
[Question] How to install whith Gapps already installed?

### ISSUE THREAD

**Issue by Mosrite** [microg/android_packages_apps_UnifiedNlp#9]
Hello, I use OmniRom with Gapps installed. Now I try to switch from Google location service to UnifiedNLP.
I downloaded the NetworkLocation.apk and put it into /system/priv-app/, afterwards I rebooted. Then I downloaded and installed the Apple and GSM plugins form F-Droid and rebooted again. But the NLP backend is not listed among settings->apps. Furthermore, my phone still uses Google's location service. How do I change this and make it work?
Thanks in advance for your help!

**Comment by mar-v-in** [comment]
I guess this problem can be closed, as everything relevant is said.

> UnifiedNlp interferes with Google Play Services, which is located in /system/priv-app/GmsCore.apk. You'll run in trouble if you try to use some google apps without original (or atleast compatible) GmsCore package - thus I clearly disadvise doing so.
