### ISSUE TITLE
UnifiedNlp is full checked but no position

### ISSUE THREAD

**Issue by Mannshoch** [microg/android_packages_apps_UnifiedNlp#92]
UnifiedNlp is full checked but no position

![unifiednlp-f-droid](https://cloud.githubusercontent.com/assets/7795891/15469650/f0bb34c6-20eb-11e6-88a5-852cda366b6b.png)

![unifiednlp](https://cloud.githubusercontent.com/assets/7795891/15469529/12103bc2-20eb-11e6-9690-8f7ccd204bb7.png)
![screenshot_2016-05-23-13-35-43](https://cloud.githubusercontent.com/assets/7795891/15469613/9dd8cdae-20eb-11e6-94f1-e9a82461a1c3.png)

**Comment by n76** [comment]
The error indicates that you have not installed a backend. Which location backend(s) have you installed.

**Comment by IzzySoft** [comment]
@n76 That's the same error I'm seeing. LocalGSMLocation backend installed, configured, and activated. Afraid the location I get comes from Google (and yes, the XPosed module is installed and activated as well). Checked the logs, see #72 

So maybe related: #88 and #76 (uh? Those two titles sound like duplicates)

**Comment by Mannshoch** [comment]
Yes it seems to bee a duplicate. Sorry that I was not able to see it.
Could I help some how? And yes My phone is a Fairphone 2 with OS 1.2.8



![f-droid](https://cloud.githubusercontent.com/assets/7795891/15485028/51d04e76-213d-11e6-9d9f-40bc51e61888.png)
![unifiednlp](https://cloud.githubusercontent.com/assets/7795891/15485032/5424925e-213d-11e6-8f9e-773b9714b918.png)
![appopsxposed](https://cloud.githubusercontent.com/assets/7795891/15485280/a7ab3382-213e-11e6-8da0-86f010079ec0.png)

**Comment by Mannshoch** [comment]
The UnifiedNlp app for Xposed seems to be really old.
https://github.com/Rawi01/XposedUnifiedNlp
xposed tells me 21.02.2015 as publishing data

**Comment by IzzySoft** [comment]
Note: [Rawi has updated XposedUnifiedNLP](https://github.com/Rawi01/XposedUnifiedNlp/issues/4#issuecomment-222001810). According to a quick test and log check, this seems to fix issues on LP/MM (I've tested it on 5.1.1).

**Comment by Mannshoch** [comment]
I Use this refreshed XposedUnifiedNLP but now I have at Start a position. But it lays in a foreign Country I never was before (Live in Switzerland)
As Update Source I use Mozilla Location Service. For a Test I reduced the Countries to some in Central Europa, it do not help:
![screenshot_2016-07-15-14-38-07](https://cloud.githubusercontent.com/assets/7795891/16874737/5830c822-4a9b-11e6-8b2a-430d4222f9f0.png)

**Comment by Mannshoch** [comment]
Lat 42 Lon 42

**Comment by mar-v-in** [comment]
Do you have the dummy backend (of Xposed module) enabled in unifiednlp settings?

**Comment by Mannshoch** [comment]
Xposed UnifiedNlp 1.0.4-Experimental Is active and all green.
LocalGsmNlpBackend from F-Droid is at version 1.4.7
In UnifiedNlp Settings is Dummy Backend and GSM Ortungsdienst (Database four days ago) activated.
Android is 5.1 and Fairphone 1.4.2

**Comment by mar-v-in** [comment]
You should disable the dummy backend

**Comment by Mannshoch** [comment]
That was the solution! What function does this Dummy Backend has?
