### ISSUE TITLE
Installation Failure "UnifiedNlp (no GAPPS)"

### ISSUE THREAD

**Issue by 74cmonty** [microg/android_packages_apps_UnifiedNlp#93]
Hello!

I have installed CM13 (13.0-20160605-NIGHTLY-ks01lte) from scratch w/o GApps.
Threema support adviced to use microG to overcome some issues related to polling.

Based on this I started installation with F-Droid and succeeded for some packages.

But the installation of UnifiedNlp (no GAPPS) fails with unknown error:
![screenshot_20160606-113538 1](https://cloud.githubusercontent.com/assets/12523591/15818776/7ed4aa82-2bdf-11e6-8cfc-36c6bffe3e78.png)

At this point I'd like to understand why this installation fails.
Furthermore it would be helpful if somebody could explain which packages should be installed:
UnifiedNlp.apk
NetworkLocation.apk
LegacyNetworkLocation.apk

This is not clear, but my understanding was that I should have UnifiedNlp (no GAPPS) installed on devices w/o Google services.

THX

**Comment by IzzySoft** [comment]
You don't need that package anymore if you've installed the latest GmsCore, as it got integrated with that. The "UnifiedNLP (no GAPPS)" is just a "legacy app" for those still using the GmsCore predecessor "NOGAPPS".

**Comment by 74cmonty** [comment]
Great! Thanks, Izzy.
I'll continue testing Android w/o Google and may come back to you

**Comment by IzzySoft** [comment]
Anytime, @74cmonty ! Be welcome to see the linked site for more privacy tips as well :)
