### ISSUE TITLE
GPS signal not found in Pokémon Go (KitKat)

### ISSUE THREAD

**Issue by alanpoulain** [microg/android_packages_apps_UnifiedNlp#96]
It seems Pokémon Go does not work as expected with UnifiedNlp.
I am in the middle of the ocean and I have this message: GPS signal not found.
Backend: GSM Location Service.
Android KitKat 4.4.4.
Am I the only one? If not any idea why?

**Comment by n76** [comment]
From comments on various forums, I suspect that Pokémon Go giving the message “GPS signal not found” could be a generic error message without actually having to do with GPS signals, etc.

That said, when you write “I am in the middle of the ocean” does that mean that you are out of range of terrestrial mobile coverage? If so, then your only positioning system that will work is the built in GPS which is independent of UnifiedNLP so this is unlikely to be a UnifiedNLP or backend issue.

**Comment by ImAnnoying** [comment]
I think what he is trying to say is that the map shows he is in the ocean, while he's not actually there...

**Comment by n76** [comment]
Ah. In that case using a tool like SatStat to get the MMC/MNC/LAC/Cell ID of the towers his phone sees would be a first step. Second step would be to see if they are in the OpenCell ID and/or Mozilla cell/mobile tower ID database he is using.

Also, on some phones, like mine, the phone only reports one cell tower so your positional accuracy is simply the coverage of the tower which might not be considered good enough for some apps.

**Comment by IzzySoft** [comment]
Guess he's on [Null Island](https://en.wikipedia.org/wiki/Null_Island). And with the heavy load the P-Servers experience, that might very well be some kind of "generic error".

**Comment by alanpoulain** [comment]
I don't think ths a

**Comment by alanpoulain** [comment]
I've done some tests with SatStat:
- GPS data seems to be OK.
- I have one tower my phone is seeing and OpenCell ID knows it. Maybe @n76 is right and it's not enough? But anywhere I go, it does not work so I'm not so sure.

**Comment by n76** [comment]
It might also be something that is needed in GmsCore that UnifiedNLP does not supply. In [this post](http://forum.xda-developers.com/showpost.php?p=67662685&postcount=1384) MaR-V-iN mentions 0.2.3-6 which seems to be a GmsCore version. There is at least [one report that Pokémon Go is working using GmsCore](http://forum.xda-developers.com/showpost.php?p=67669993&postcount=1396).

**Comment by alanpoulain** [comment]
I have updated GmsCore to 0.2.3-6. It works now thanks!
It seems Pokémon Go does not use network based location (because of the unprecise accuracy?).

**Comment by mar-v-in** [comment]
@alanpoulain Pokemon Go will use network based location if accuracy is high enough. I don't know the exact limit, but I sometimes got working location in pokemon go with gps disabled

**Comment by alanpoulain** [comment]
OK I'll try sometimes to see, thank you.
