### ISSUE TITLE
F-Droid cannot replace Android's version with your no-GAPPS version

### ISSUE THREAD

**Issue by gloschtla** [microg/android_packages_apps_UnifiedNlp#97]
F-Droid offers µg UnifiedNlp (no GAPPS) in the list of Updates.
When I try to update, I get this message: "The new version is signed with a different key to the old one. To install the new version, the old one must be uninstalled first."
When I try to uninstall Android's version, that appears in F-Droid in the list of installed apps, i get this message: "Failed to uninstall due to an unknown error"

**Comment by Shadow53** [comment]
You probably have some form of GApps installed, either from a GApps package or from the microG implementation. UnifiedNLP (no GAPPS) works basically by pretending to be Google's location provider from GApps, using the same package name.

If you are using microG, it has UnifiedNLP built in and you can use the back ends from there. If you are using Google's GApps, you'll have to use the UnifiedNLP (GAPPS) package instead or use Google's own location provider (or remove the proprietary GApps and use microG instead).
